<?php
/**
 * 首页
 *
 * @author Administrator
 *
 */

namespace app\controllers\wap;


use common\components\PcController;
use common\components\WapController;
use common\models\Content;
use Yii;
use common\Cms;
use common\models\Category;
use yii\helpers\Json;
use yii\helpers\Url;


class ArticleController extends WapController
{
    public $fenlei = ['zuixin' => 75, 'xinwen' => 76, 'gonggao' => 77, 'huodong' => 78, 'gonglue' => 79];

    public function beforeAction($action)
    {
        return parent::beforeAction($action, 1); // TODO: Change the autogenerated stub
    }

    /**
     * 新闻列表页面
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index.html');
        $type = Cms::getGetValue('type', 'zuixin');
        return $this->render('index.html', [
            'type' => $type,
        ]);
    }

    /**
     * 新闻列表
     * @return string
     */
    public function actionAjaxNews()
    {

        $type = Cms::getGetValue('type', 'zuixin');

        if (!key_exists($type, $this->fenlei)) {
            $categoryId = $this->fenlei['zuixin'];
        } else {
            $categoryId = $this->fenlei[$type];
        }

        $data = self::ajaxGetNews($categoryId);

        $testType = Cms::getGetValue('testType', 0);
        if ($testType) {
            pr($data, 1);
        }

        echo Json::encode($data);
        exit;
    }

    /**新闻详情
     * @return string
     */
    public function actionDetail()
    {
        $testType = Cms::getGetValue('testType', 0);
        $id = Cms::getGetValue('id');
        if (!$id) {
            echo "<script>alert('文章ID不能为空');location.href='/wap/article/index.html'</script>";
            exit;
        }
        $content = $this->getContentDetail($id);
        if ($content && !key_exists('body', $content)) {
            $content = array_merge($content, array('body' => ''));
        }
        if ($testType) {
            pr($content, 1);
        }
//        pr($content, 1);
        return $this->renderPartial('detail.html', $content);
    }

    public function actionTest()
    {
        $type = Cms::getGetValue('testType');
        if (!$type) {
            echo '不存在';exit;
        }
        $_GET['testType'] = 1;
        $action = 'action'.$type;
        $this->$action();
    }

}
