<?php
/**
 * 首页
 *
 * @author Administrator
 *
 */

namespace app\controllers\wap;


use common\components\HomeController;
use common\Cms;

use yii\web\Controller;

class SiteController extends \common\components\WapController
{
    public function beforeAction($action)
    {
        return parent::beforeAction($action, 1); // TODO: Change the autogenerated stub
    }

    public function actionCover()
    {
        return $this->render('cover');
    }

    public function actionIndex()
    {
        $testType = Cms::getGetValue('testType', 0);
        $data = array();
        $index_video = $this->getRecommend('index_video', 1);   //首页推广视频
        $data['index_video'] = $index_video[0];

        $index_banner = $this->getRecommend('index_banner');   //首页banner
        $data['index_banner'] = $index_banner;

        $data['zuixin'] = $this->getContentArr(75, 10);    //最新
        $data['xinwen'] = $this->getContentArr(76, 10);    //新闻
        $data['gonggao'] = $this->getContentArr(77, 10);    //公告
        $data['huodong'] = $this->getContentArr(78, 10);    //活动
        $data['gonglue'] = $this->getContentArr(79, 10);    //攻略

        if ($testType == 1) {
            pr($data, 1);
        }
        return $this->renderPartial('index.html', $data);
    }

    public function actionError()
    {
        return $this->render('error');
    }

    public function actionTest($type = '', $id = '')
    {
        if (!$type) {
            echo '不存在';exit;
        }
        $_GET['testType'] = 1;
        $action = 'action'.$type;
        $id = Cms::getGetValue('id', 0);
        if ($id) {
            $this->$action($id);
        } else {
            $this->$action();
        }

    }
}
