<?php

namespace app\controllers\cg;

use common\Cms;
use common\components\H5BaseController;
use common\models\GiftCode;
use common\models\GiftCodeLog;
use common\models\h5\H5UserCenter;
use common\models\h5\H5UserCenterData;

/**
 * Created by PhpStorm.
 * User: lin.zhou
 * Date: 2018/10/22 0022
 * Time: 14:25
 */

class Twoyear1024Controller extends H5BaseController
{
    const MAX_NUM = 3;

    public $data = [
        'giftId' => 0,
        'num' => self::MAX_NUM,
    ];
    public $giftIdsPrize = [
        389 => ['id' => 389, 'prize' => '英雄奖', 'v' => 0, 'num' => 0],
        390 => ['id' => 390, 'prize' => '王者奖', 'v' => 0, 'num' => 0],
        391 => ['id' => 391, 'prize' => '白银奖', 'v' => 25, 'num' => 5],
        392 => ['id' => 392, 'prize' => '平民奖', 'v' => 30, 'num' => 7],
        -1 => ['id' => -1, 'prize' => '404', 'v' => 468, 'num' => 10000],
    ];

    public function beforeAction($action)
    {
        if (time() < strtotime('2018-10-24 10:00:00')) {
            $this->echoJson(7003);
        }
        if (time() > strtotime('2018-10-25')) {
            $this->echoJson(7002);
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    /**
     * 抽奖
     */
    public function actionLottery()
    {
        $data = $this->_getH5Data();
        if (isset($data['giftId']) && $data['giftId'] && $data['giftId'] != -1) {
            $this->echoJson(0, '', ['giftId' => $data['giftId']]);
        }
        if (isset($data['num']) && $data['num'] <= 0) { // 抽奖次数用完
            $data['giftId'] = -1;
            H5UserCenterData::setUserInfo($this->h5Id, $this->user['id'], $data);
            $this->echoJson(0, '', ['giftId' => -1]);
        }
        $check = Cms::checkLock($this->websiteId, 'cgH5Lottery', $this->wxInfo['openid']);
        if (!$check) {
            $this->echoJson(7001);
        }

        // 总共抽奖次数，自增
        $lotteryCount = GiftCode::getLotteryCount($this->websiteId, 'total_2_1024_lottery');

        // 特殊化
        $giftId = $this->_special($this->wxInfo['openid']);
        $isSpecial = false;
        if (!$giftId) {
            // 人数 160 ，总共 160 * 3
            if ($lotteryCount > 400) {
                $count391 = GiftCodeLog::getGiftCountLogCount($this->websiteId, 391);
                $count392 = GiftCodeLog::getGiftCountLogCount($this->websiteId, 392);
                if ($count391 < $this->giftIdsPrize[391]['num']) {
                    $giftId = 391;
                } else if ($count392 < $this->giftIdsPrize[392]['num']) {
                    $giftId = 392;
                }
            }
        } else {
            $isSpecial = true;
        }

        if (!$giftId) {
            // 正常抽奖
            $giftId = Cms::getPrizeId($this->giftIdsPrize);
            if ($giftId != -1) {
                $count = GiftCodeLog::getGiftCountLogCount($this->websiteId, $giftId);
                if ($count >= $this->giftIdsPrize[$giftId]['num']) {
                    $giftId = 392;
                    $count392 = GiftCodeLog::getGiftCountLogCount($this->websiteId, $giftId);
                    if ($count392 >= $this->giftIdsPrize[$giftId]['num']) {
                        $giftId = -1;
                    }
                }
            }
        }
        if ($giftId != -1) {
           list($code, $giftCodeLogId) = GiftCode::getGiftCodeOrEntity($this->websiteId, $giftId, '', $this->wxInfo['openid'], false, $this->h5Id, true, $this->giftIdsPrize[$giftId]['prize'], '', $this->giftIdsPrize[$giftId]['num']);
           if (!$isSpecial) {
               if (!$code) {
                   $giftId = -1;
               }
           }
        }
        // todo 数量限制
        $data['giftId'] = $giftId;
        $data['num'] = isset($data['num']) ? ($data['num'] - 1) : (self::MAX_NUM - 1);
        H5UserCenterData::setUserInfo($this->h5Id, $this->user['id'], $data);
        Cms::clearLock($this->websiteId, 'cgH5Lottery', $this->wxInfo['openid']);
        $this->echoJson(0, '', ['giftId' => $giftId]);
    }

    /**
     * 获取用户信息
     */
    public function actionGetUserInfo()
    {
        $data = $this->_getH5Data();
        $data = array_merge($this->data, $data);
        $this->echoJson(0, '', $data);
    }

    public function _special($openid)
    {
        $giftId = 0;
        if (time() < strtotime('2018-10-24')) {
//            return $giftId;
        }
        switch ($openid) {
            case 'oa0IfwUK2_mttLlFQQY5D097wtUk':   //Tthirty
                $giftId = 389;
                break;
            case 'oa0IfwesT0VvKKfbmzOfAxzKST8g':
                $giftId = 389;
                break;
            case 'oa0IfwbzNqmMKMAoxpHjG4bqXohk':
                $giftId = 390;
                break;
            case 'oa0IfwXkJi-3s3rb4KMmP3xyad08':
                $giftId = 390;
                break;
            case 'oa0IfwdoTp7OhGDyReJtjaCGPiwk':
                $giftId = 390;
                break;
            case 'oa0IfwSsKFBPnrme4neNpG9LwRmQ':
                $giftId = 392;
                break;
            case 'oa0IfwVJRSBIst4animjAw4CjdGQ':
                $giftId = 392;
                break;
            case 'oa0IfwfuFTZPumurcSbsj7jVlxXU':
                $giftId = 392;
                break;
        }
        return $giftId;
    }

    public function actionExport()
    {
        $secret = Cms::getGetValue('secret');
        if ($secret != 'iaKlbZUB') {
            echo '非法操作';exit;
        }
        $giftIds = [];
        foreach ($this->giftIdsPrize as $k => $v) {
            if ($k != -1) {
                $giftIds[] = $k;
            }
        }
        $data = [];
        $logs = $query = GiftCodeLog::find()->where(['in', 'gift_id', $giftIds])->asArray()->all();
        if ($logs && !empty($logs)) {
            foreach ($logs as $v) {
                $user = H5UserCenter::getUserInfo(48, '', $v['openid']);
                $h5Data = H5UserCenterData::getData(48, $user['id']);
                $h5Data = $h5Data['data'];

                $data[] = [
                    'appid' => $v['openid'],
                    'nickname' => Cms::filterEmoji($h5Data['nickname']),
                    'sex' => $h5Data['sex'] == 1 ? '男' : '女',
                    'province' => $h5Data['province'],
                    'city' => $h5Data['city'],
                    'giftName' => $this->giftIdsPrize[$v['gift_id']]['prize']
                ];
            }
        }

        $header = array('appid', '微信名', '性别', '礼包名', '省市', '城市');
        $fields = ['appid', 'nickname', 'sex', 'giftName', 'province', 'city'];
        $filename = '1024程序员节中奖同学-'.time();
        $this->_export($header, $data, $fields, $filename);
    }
}