<?php

namespace app\modules\game\controllers;

use common\Cms;
use common\components\PcController;
use common\helpers\Utils;
use common\models\fc\GameActive;
use common\models\fc\GameDaoju;
use common\models\fc\GameScoreLog;
use common\models\VerifyCode;
use yii\helpers\Json;
use yii\helpers\Url;
use Yii;
use SmsUtils;

/**
 * Created by yiicms.
 * User: Administrator
 * Author: druphliu@gmail.com
 * Date: 2015/6/12
 * Time: 19:35
 */
class HandleController extends PcController
{
    private $appid = 'wx8ab5370e12252776';
    private $secret = 'fd0c75ef5f2bb154b1b25d66a4d79963';
    /*private $appid = 'wx0c3037e0a311908e';
    private $secret = 'cb9577372e1f7e13d4a9c648d0c4ba7c';*/ //测试账号
    private $result = array('status' => 0, 'msg' => '', 'data' => '');

    private $exchange = array('chemi' => 1500, 'guanjun' => 5000);

    private $shareData;
    private $openid;

    public $enableCsrfValidation=false;

    public function beforeAction($action, $isNoLayout = 0)
    {
//Cms::setSession('phone', 15910557051);
//Cms::setSession('openid', 'oa0IfwTLU3aVW0D6YFnB7UkuPH1U');
        $this->openid = Cms::getSession('openid');
        $notice = 'Wm3WZYTPz0wzccnW';
        $time = time();
        $appid = 'wx29f1abecd4fc85d6';
        //$appid='wx0c3037e0a311908e';//测试
        $protocol = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off' || $_SERVER['SERVER_PORT'] == 443) ? "https://" : "http://";
        $href_url = "$protocol$_SERVER[HTTP_HOST]$_SERVER[REQUEST_URI]";
        $signature = $this->_sign($href_url, $notice, $time);
        $shareUrl = Url::to(['handle/index'], true);
        $shareImage = STATIC_DOMAIN . 'kangshifu/img/share.jpg';
                $shareTitle = '100%中奖，机不可失！';
        $shareDesc = '最好吃的康师傅汤面套餐，最刺激的掌上真漂移手游，最丰厚的专属奖品，错过再等无数年！';
	    $this->shareData = array('signature' => $signature, 'shareTime' => $time, 'notice' => $notice, 'shareUrl' => $shareUrl, 'appid' => $appid, 'shareTitle' => $shareTitle, 'shareDesc' => $shareDesc);
        return parent::beforeAction($action, $isNoLayout); // TODO: Change the autogenerated stub
    }

    public function actionIndex()
    {

        $phone = Cms::getSession('phone');
        $info = GameActive::find()->where('phone=:phone', array(':phone' => $phone))->one();

        return $this->renderPartial('index', array_merge(array('info' => $info), $this->shareData));
    }

    public function actionExplain()
    {
        $code = Cms::getGetValue('code');
        if (Cms::isPost()) {
            $phone = Cms::getPostValue('phone');
            $code = Cms::getPostValue('verifycode');
            if ($code && $phone) {
                $phoneModel = VerifyCode::find()->where('phone=:phone', array(':phone' => $phone))->one();
                if ($phoneModel) {
                    if ($phoneModel->verify == $code && $phoneModel->count > 0) {
                        Cms::setSession('phone', $phone);
                        $this->result['status'] = 1;
                        $gameModel = GameActive::find()->where('phone=:phone', array(':phone' => $phone))->one();
                        if (!$gameModel) {
                            $gameModel = new GameActive();
                            $gameModel->phone = $phone.'';
                            $gameModel->openid = $this->openid;
                            $gameModel->score = 0;
                            $gameModel->save();
                        } else {
                            $gameModel->openid = $this->openid;
                            $gameModel->save();
                        }

                    } else {
                        $this->result['msg'] = '验证码有误';
                    }
                    $phoneModel->count -= 1;
                    $phoneModel->count = $phoneModel->count > 0 ? $phoneModel->count : 0;
                    $phoneModel->save();
                } else {
                    $this->result['msg'] = '验证码有误';
                }

            } else {
                $this->result['msg'] = '不能为空';
            }
            die(Json::encode($this->result));
        }

        if ($code) {
            $url = 'https://api.weixin.qq.com/sns/oauth2/access_token?appid=' . $this->appid . '&secret=' . $this->secret . '&code=' . $code . '&grant_type=authorization_code';
            $result = Utils::sendHttpRequest($url);
            $result = Json::decode($result['content']);
            if (isset($result['access_token'])) {
                Cms::setSession('openid', $result['openid']);
            }
        } else {
            if (!$this->openid) {
                $REDIRECT_URI = 'http://game.yingxiong.com/fc_wx_game/';
                $url = 'https://open.weixin.qq.com/connect/oauth2/authorize?appid=' . $this->appid . '&redirect_uri=' . $REDIRECT_URI . '&response_type=code&scope=snsapi_base#wechat_redirect';
                header("Location:" . $url);
            } else {
                $info = GameActive::find()->where('openid=:openid', array(':openid' => Cms::getSession('openid')))->one();
                if ($info) {
                    Cms::setSession('phone', $info->phone);
                    return $this->redirect(array('/game/handle/main'));
                }

            }
        }
        return $this->renderPartial('explain', $this->shareData);
    }

    public function actionGetVerify()
    {
        $phone = Cms::getGetValue('phone');
        //随机生成验证码
        $verify = rand(1000, 9999);
        //查看是否已经发送过,无论是否成功注册
        $model = VerifyCode::find()->where('phone=:phone', array(':phone' => $phone));
        if ($model) {
            if ($model->count >= 3)
                $this->result['status'] = 3;
            elseif ($model->created_at > time() - 30)//30秒内只能提交一次
                $this->result['status'] = 2;
            else {
                //重新发送验证码
                $model->verify = $verify;
                $model->created_at = time();
                $model->count += 1;
                $model->save();
                //发送短信
                $content = '验证码为:' . $verify . ',将用于《一起来飞车》康师傅活动登录,请于30分钟内输入';
                SmsUtils::sendSms($phone, $content);
                $this->result['status'] = 1;
            }
        } else {
            $model = new VerifyCode();
            if ($model) {
                $model->verify = $verify;
                $model->phone = $phone;
                $model->created_at = time();
                $model->count = 1;
                $model->save();
                //发送短信
                $content = '验证码为:' . $verify . ',将用于《一起来飞车》康师傅活动登录,请于30分钟内输入';
                SmsUtils::sendSms($phone, $content);
                $this->result['status'] = 1;
            }
        }
        die(CJSON::encode($this->result));
    }


    /**
     * 主页面
     */
    public function actionMain()
    {
        $result = $this->__logined();
        if ($result) {
            return $result;
        }
        $phone = Cms::getSession('phone');
        $info = GameActive::find()->where('phone=:phone', array(':phone' => $phone))->one();
        return $this->renderPartial('main', array_merge(array('info' => $info), $this->shareData));
    }

    public function actionShop()
    {
        $result = $this->__logined();
        if ($result) {
            return $result;
        }
        $phone = Cms::getSession('phone');
        $info = GameActive::find()->where('phone=:phone', array(':phone' => $phone))->one();
        $count = $this->__get_lottery_count($phone);
        return $this->renderPartial('shop', array_merge(array('info' => $info, 'exchange' => $this->exchange,
            'count' => $count, 'total_count' => $info->gift_count), $this->shareData));
    }

    public function actionResult()
    {
        $score = 0;
        $result = $this->__logined();
        if ($result) {
            return $result;
        }
        $phone = Cms::getSession('phone');
        $info = GameActive::find()->where('phone=:phone', array(':phone' => $phone))->one();
        $id = $_REQUEST['id'];
        $log = GameScoreLog::findOne($id);
        if ($log) {
            if ($log->status == 0) {
                $score = $log->score;
                $log->status = 1;
                $log->save();
            }
        }

        return $this->renderPartial('result', array_merge(array('info' => $info, 'score' => $score), $this->shareData));
    }

    public function actionLogout()
    {
        Cms::setSession('phone', '');
        return $this->redirect(array('/game/handle/index'));

    }

    public function actionCheck()
    {
        $phone = $_REQUEST['phone'];
        $logCount = GameScoreLog::find()->where('phone=:phone and created_at>:start and created_at<:end and type=:type and score>0',
            array(':phone' => $phone, ':start' => date('Y-m-d') . ' 0:0:0', ':end' => date('Y-m-d') . ' 23:59:59', ':type' => 'game'))->count();
        if ($logCount < 2) {
            $this->result['status'] = 1;
            $model = new GameScoreLog();
            $model->phone = $phone.'';
            $model->type = 'game';
            $model->score = 0;
            $model->save();
        } else {
            $this->result['msg'] = '今日次数已用完，明日再来吧';
        }
        die(Json::encode($this->result));
    }

    public function actionScore()
    {

        if (Cms::isPost()) {
            $phone = $_REQUEST['phone'];
            $score = $_REQUEST['score'];
            $model = GameScoreLog::find()->where('phone=:phone and type=:type and score<=0', array(':phone' => $phone, ':type' => 'game'))->one();
            if ($model) {
                $sql = 'update {{cms_fc_game_active}} set score=score+' . $score . ' where phone=' . $phone;
                Yii::$app->db->createCommand($sql)->query();
                $model->desc = '玩了小游戏获得了' . $score . '积分';
                $model->score = $score;
                $model->save();
                $this->result['status'] = 1;
                $this->result['data'] = Url::to(['/game/handle/result', 'id' => $model->id], true);
            }
        }
        die(Json::encode($this->result));
    }

    /**
     * 已转成YII2
     */
    public function actionExchange()
    {
        if (Cms::isPost()) {
            $phone = Cms::getSession('phone');
            $info = GameActive::find()->where('phone=:phone', array(':phone' => $phone))->one();
            $db = Yii::$app->db;
            $id = Cms::getPostValue('id');
            $score = isset($this->exchange[$id]) ? $this->exchange[$id] : 0;
            $level = $id == 'chemi' ? 2 : 1;
            //是否已经兑换过
            $log = GameScoreLog::find()->where('phone=:phone and created_at>:start and created_at<:end and type=:type',
                array(':phone' => $phone, ':start' => date('Y-m-d') . ' 0:0:0', ':end' => date('Y-m-d') . ' 23:59:59', ':type' => 'daoju'))->all();
            $logCount = $logLevel = 0;
            if ($log) {
                foreach ($log as $l) {
                    $logLevel = abs($l['score']) == $this->exchange['chemi'] ? 2 : 1;
                    $logCount += 1;
                }
            }

            if ($score > 0 && $info->score >= $score && $logCount <= 1 && $logLevel != $level) {

                $daoju = GameDaoju::find()->where('status=0 and level=' . $level)->one();
                if ($daoju) {
                    $transaction = $db->beginTransaction();
                    try {
                        $daoju = GameDaoju::findBySql("SELECT * FROM {{cms_fc_game_daoju}} WHERE id=$daoju->id FOR UPDATE;")->one();

                        if ($daoju && $daoju->status == 0) {
                            //扣积分，更新
                            $info->score -= $score;
                            $info->save();
                            $daoju->status = 1;
                            $daoju->completed_at = date('Y-m-d H:i:s');
                            $daoju->phone = $phone;
                            $daoju->save();
                            $log = new GameScoreLog();
                            $log->type = 'daoju';
                            $log->phone = $phone.'';
                            $log->score = -$score;
                            $log->code = $daoju->code;
                            $log->desc = '兑换了道具' . $daoju->code;
                            $log->save();
                            $transaction->commit();
                            $this->result['msg'] = '您已兑换成功,礼包码:<i>' . $daoju['code'] . '</i>';
                        } else {
                            $this->result['msg'] = '系统异常稍后再来!';
                            $transaction->rollBack();
                        }

                    } catch
                    (Exception $e) {
                        $this->result['msg'] = '系统异常稍后再来!';
                        $transaction->rollBack();
                    }
                } else {
                    $this->result['msg'] = '你兑换的礼品没有了!';
                }

            } else {
                if ($logCount >= 2 || $logLevel == $level)
                    $this->result['msg'] = '今日已经兑换过该礼包';
                else
                    $this->result['msg'] = '积分不足，无法兑换';
            }
            $this->result['data']['score'] = $info->score;
        }
        die(Json::encode($this->result));
    }

    /**
     * 已转成YII2
     */
    public function actionCdKey()
    {
        if (Cms::isPost()) {
            $db = Yii::$app->db;
            $phone = Cms::getSession('phone');
            $info = GameActive::find()->where('phone=:phone', array(':phone' => $phone))->one();
            $key = trim(strip_tags(Cms::getPostValue('key')));
            if ($key) {
                $sql = 'select * from {{cms_fc_game_cd_key}} where code="' . $key . '"';
                $result = $db->createCommand($sql)->queryOne();

                $date = date('Y-m-d H:i:d');
                if ($result && $result['status'] == 0) {
                    $sql = 'update {{cms_fc_game_cd_key}} set status=1,completed_at="' . $date . '",phone="' . $phone . '" where id=' . $result['id'];
                    $db->createCommand($sql)->query();
                    $info->gift_count += 1;
                    $info->score += 500;
                    $info->save();
                    $count = $this->__get_lottery_count($phone);
                    $this->result['status'] = 1;
                    $this->result['msg'] = '兑换成功!';
                    $this->result['data']['total_count'] = $info->gift_count;
                    $this->result['data']['today_count'] = $count;
                    $this->result['data']['score'] = $info->score;
                } elseif ($result && $result['status'] == 1) {
                    $this->result['msg'] = '你的CD-key已经兑换过了';
                } else {
                    $this->result['msg'] = '请输入正确的CD-key';
                }
            } else {
                $this->result['msg'] = '请输入正确的CD-key';
            }
        }
        die(Json::encode($this->result));
    }

    public function actionLottery()
    {
        $db = Yii::$app->db;
        $phone = Cms::getPostValue('phone');
        //判断是否还可以抽奖
        $lCount = $this->__get_lottery_count($phone);
        if ($lCount <= 0)
            die(Json::encode($this->result));
        /*
         * 奖项数组
         * 是一个二维数组，记录了所有本次抽奖的奖项信息，
         * 其中id表示中奖等级，prize表示奖品，v表示中奖概率。
         * 注意其中的v必须为整数，你可以将对应的 奖项的v设置成0，即意味着该奖项抽中的几率是0，
         * 数组中v的总和（基数），基数越大越能体现概率的准确性。
         * 本例中v的总和为100，那么平板电脑对应的 中奖概率就是1%，
         * 如果v的总和是10000，那中奖概率就是万分之一了。
         *
         */
        $prize_arr = array(
            '0' => array('id' => 1, 'index' => 0, 'prize' => '游戏礼包Ⅰ', 'v' => 2100000),
            '1' => array('id' => 2, 'index' => 1, 'prize' => '游戏礼包Ⅱ', 'v' => 750000),
            '2' => array('id' => 3, 'index' => 2, 'prize' => '游戏礼包Ⅲ', 'v' => 150000),
            '3' => array('id' => 8, 'index' => 3, 'prize' => '游戏周边', 'v' => 0),
            '4' => array('id' => 5, 'index' => 4, 'prize' => '谢谢惠顾', 'v' => 0),
            '5' => array('id' => 6, 'index' => 5, 'prize' => 'Iwatch', 'v' => 0),
            '6' => array('id' => 7, 'index' => 6, 'prize' => '暴风魔镜', 'v' => 0),
            '7' => array('id' => 4, 'index' => 7, 'prize' => '游戏礼包Ⅳ', 'v' => 3),
        );

        /*
         * 每次前端页面的请求，PHP循环奖项设置数组，
         * 通过概率计算函数get_rand获取抽中的奖项id。
         * 将中奖奖品保存在数组$res['yes']中，
         * 而剩下的未中奖的信息保存在$res['no']中，
         * 最后输出json个数数据给前端页面。
         */
        foreach ($prize_arr as $key => $val) {
            $arr[$val['id']] = $val['v'];
            $arr_index[$val['index']] = $val['v'];
        }
        $rid = $this->__get_rand($arr); //根据概率获取奖项id

        $res['yes'] = $prize_arr[$rid - 1]; //中奖项
        unset($prize_arr[$rid - 1]); //将中奖项从数组中剔除，剩下未中奖项
        shuffle($prize_arr); //打乱数组顺序

        for ($i = 0; $i < count($prize_arr); $i++) {
            $pr[] = $prize_arr[$i];
        }
        $res['no'] = $pr;
        //取对应的奖品
        list($msg, $index, $code,$prize) = $this->__get_gift($res, $phone, $prize_arr);
        $sql = 'update {{cms_fc_game_active}} set gift_count=gift_count-1 where phone="' . $phone . '"';
        $db->createCommand($sql)->query();
        //保存数据
        $log = new GameScoreLog();
        $log->type = 'gift';
        $log->phone = $phone.'';
        $log->code = $code;
        $log->desc = '您已获得"'.$prize.'",礼包码为:'.$code;
        $log->save();
        $this->result['msg'] = $msg;
        $this->result['data']['prize'] = $index;
        $this->result['status'] = 1;
        die(Json::encode($this->result));
    }


    private function __get_gift($res, $phone, $prize_arr)
    {
        file_put_contents('1', var_export($res['yes'], true), FILE_APPEND);
        $code = $prize='';
        $db = Yii::$app->db;
        $sql = 'select * from {{cms_fc_game_gift}} where level=' . $res['yes']['id'] . ' and status=0';
        file_put_contents('sql', $sql . "\n", FILE_APPEND);
        $result = $db->createCommand($sql)->queryOne();
        if ($result) {
            $transaction = $db->beginTransaction();
            try {
                $sql = 'select * from {{cms_fc_game_gift}} where id=' . $result['id'] . '  FOR UPDATE';
                $gift = $db->createCommand($sql)->queryOne();
                if ($gift && $gift['status'] == 0) {
                    $code = $gift['code'];
                    $sql = 'update {{cms_fc_game_gift}} set status=1,phone="' . $phone . '" where id=' . $result['id'];
                    $db->createCommand($sql)->query();
                    $msg = '您已获得<span>“' . $res['yes']['prize'] . '”,</span>礼包码为：' . $code . '请到<i>“我的奖励”查看!</i>';
                    $prize = $res['yes']['prize'];
                    $index = $res['yes']['index'];
                    $transaction->commit();
                } else {
                    $transaction->rollBack();
                    //奖品没了,设置为第一个中奖
                    if ($res['yes']['index'] != 8) {
                        $res['yes'] = $prize_arr[0];
                        $this->__get_gift($res, $phone, $prize_arr);
                    } else {
                        $msg = '谢谢惠顾';
                        $index = 4;
                    }
                }

            } catch
            (Exception $e) {
                print_r($e);
                $msg = '谢谢惠顾';
                $index = 4;
            }
        } else {
            //奖品没了,设置为第一个中奖
            if ($res['yes']['id'] != 1) {
                $res['yes'] = $prize_arr[0];
                file_put_contents('res', var_export($res['yes'], true), FILE_APPEND);
                $this->__get_gift($res, $phone, $prize_arr);
            } else {
                $msg = '谢谢惠顾';
                $index = 4;
            }
        }
        return array($msg, $index, $code,$prize);
    }

    public function actionLog()
    {
        $phone = Cms::getSession('phone');
        $info = GameActive::find()->where('phone=:phone', array(':phone' => $phone))->one();
        $log = GameScoreLog::find()->where('phone=:phone', [':phone' => $phone])->orderBy('id')->all();
        return $this->renderPartial('log', array_merge(array('info' => $info, 'log' => $log), $this->shareData));
    }

    private function __get_rand($proArr)
    {
        $result = '';
        //概率数组的总概率精度
        $proSum = array_sum($proArr);
        //概率数组循环
        foreach ($proArr as $key => $proCur) {
            $randNum = mt_rand(1, $proSum);
            if ($randNum <= $proCur) {
                $result = $key;
                break;
            } else {
                $proSum -= $proCur;
            }
        }
        unset ($proArr);
        return $result;
    }

    private function __get_lottery_count($phone)
    {
        $count = 0;
        $info = GameActive::find()->where('phone=:phone', array(':phone' => $phone))->one();
        if ($info->gift_count > 0) {
            $logCount = GameScoreLog::find()->where('phone=:phone and created_at>:start and created_at<:end and type=:type',
                array(':phone' => $phone, ':start' => date('Y-m-d') . ' 0:0:0', ':end' => date('Y-m-d') . ' 23:59:59', ':type' => 'gift'))->count();
            $count = 2 - $logCount;
            $count = $info->gift_count > $count ? $count : $info->gift_count;
        }
        return $count >= 0 ? $count : 0;
    }

    private function __logined()
    {
        if (Cms::getSession('openid')) {
            $info = GameActive::find()->where('openid=:openid', array(':openid' => Cms::getSession('openid')))->one();
            if ($info)
                Cms::setSession('phone', $info->phone);
        }
        if (!Cms::getSession('phone'))
            return $this->redirect(['/game/handle/explain']);
    }

    private function _sign($href_url, $notice, $time)
    {
        $secret='c0de060471c773e25870d2a05c800826';
        $appid = 'wx29f1abecd4fc85d6';
       // $secret = 'cb9577372e1f7e13d4a9c648d0c4ba7c';//测试
        //$appid='wx0c3037e0a311908e';//测试
        $signature = '';
//		echo $href_url;exit;
        $url = 'https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=%s&secret=%s';
        $url = sprintf($url, $appid, $secret);
        $content = Utils::sendHttpRequest($url);
        $wx_result = Json::decode($content['content']);
        if (isset($wx_result['access_token'])) {
            $token = $wx_result['access_token'];
            $url = 'https://api.weixin.qq.com/cgi-bin/ticket/getticket?access_token=%s&type=jsapi';
            $url = sprintf($url, $token);
            $content = Utils::sendHttpRequest($url);
            $wx_result = Json::decode($content['content']);
            if (isset($wx_result['errcode']) && $wx_result['errcode'] == 0) {
                $ticket = $wx_result['ticket'];
                $str = "jsapi_ticket=$ticket&noncestr=$notice&timestamp=$time&url=$href_url";//echo $str;
                $signature = sha1($str);
            }
        }
        return $signature;
    }


}
