<?php

namespace app\controllers\lszt;

use common\cache\h5\lszt\H5LsztLogCache;
use common\Cms;
use common\components\H5BaseController;
use common\components\HomeController;
use common\models\GiftCode;
use common\models\h5\H5Data;
use common\models\h5\H5Log;

/**
 * Created by PhpStorm.
 * User: lin.zhou
 * Date: 2018/8/2
 * Time: 10:14
 */
class OldplayerController extends H5BaseController
{
    public $h5Id;
    public $h5UserId;
    public $openId;
    public $h5WebsiteId;


    public function beforeAction($action)
    {
        $this->h5Id = Cms::getSession('h5_id');
        $this->h5UserId = Cms::getSession('h5_user_id');
        $this->openId = Cms::getSession('h5_wx_openid_'.$this->h5Id);
        $this->h5WebsiteId = Cms::getSession('h5_website_id');
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    /**
     * 签到
     */
    public function actionSign()
    {
        $this->_checkWxLogin();
        $name = Cms::getPostValue('name');
        $year = Cms::getPostValue('year');
        $content = Cms::getPostValue('content');
        $this->_checkInput($name, $year, $content);
        $year = date('Y') - $year + 1;
        $data = ['name' => $name, 'year' => $year, 'content' => $content];
        $log = H5Log::addLog($this->h5Id, $this->h5UserId, $data);
        $cache = new H5LsztLogCache();
        $log['data'] = $data;
        $cache->pushLog($log);
        $this->ajaxOutPut(['status' => 0, 'msg' => '成功']);
    }

    /**
     * 获取所有玩家发送的签到信息
     */
    public function actionGetSignLog()
    {
        $data = [];
        $cache = new H5LsztLogCache();
        $data['data'] = $cache->getLog();
        $this->ajaxOutPut(['status' => 0, 'msg' => $data]);
    }

    /**
     * 获取礼包
     */
    public function actionGetGift()
    {
        $this->_checkWxLogin();
        $res = GiftCode::getUserGiftCode($this->website_id, 346, '', $this->openId);
        if (!$res) {
            $this->ajaxOutPut(['status' => -1, 'msg' => '礼包码已经领取完']);
        }
        $code = $res;
        $params = [
            'data' => [
                'gift_code' => $code
            ],
        ];
        H5Data::setUserInfo($this->h5WebsiteId, $this->h5Id, $this->openId, $params);
        $this->ajaxOutPut(['status' => 0, 'msg' => $code]);
    }

    private function _checkInput($name, $year, $content)
    {
        if (!$name) {
            $this->ajaxOutPut(['status' => -1, 'msg' => '昵称不能为空']);
        }
        if (!$year || !is_numeric($year) || ($year < '2006') || ($year > date('Y'))) {
            $this->ajaxOutPut(['status' => -1, 'msg' => '年龄不合法']);
        }
        if (!$content) {
            $this->ajaxOutPut(['status' => -1, 'msg' => '签到语不能为空']);
        }
    }

    private function _checkWxLogin()
    {
        if (!$this->h5Id || !$this->h5UserId || !$this->openId) {
            $this->ajaxOutPut(['status' => -1, 'msg' => '登录失败，请重新登录']);
        }
    }
}