<?php
/**
 * Created by PhpStorm.
 * User: lin.zhou
 * Date: 2018/10/10 0010
 * Time: 18:18
 */

namespace app\controllers\wap;


use common\components\WapController;

class YyController extends WapController
{
    public function beforeAction($action, $isNoLayout = 0)
    {
        header('Location:http://cdnstatic.yingxiong.com/common/jqqd/index1.html');
        exit;
        return parent::beforeAction($action, $isNoLayout); // TODO: Change the autogenerated stub
    }

    public function actionIndex()
    {
        return $this->renderPartial("index.html");
    }

    /**
     * 受邀请页
     * @return false|string
     */
    public function actionInvite()
    {
        return $this->renderPartial("invite.html");
    }
}