<?php
/**
 * 首页
 *
 * @author Administrator
 *
 */

namespace app\controllers;


use common\Cms;
use common\components\PcController;
use common\models\GiftCode;
use common\models\UserCenter;
use common\models\UserCenterData;
use common\models\YuyueStatModel;
use yii\base\Exception;


class SiteController extends PcController
{
    const GIFT_ID = 347;
    const GIFT_ID_NEW_PLAYER = 349;

    const GIFT_ID_NEW_COVER = 393;
    const GIFT_ID_NEW_COVER_NEW_PLAYER = 394;
    const GIFT_ID_NEW_COVER_OLD_PLAYER = 395;

    public $data = [
        'is_yuyue' => 0,
        'gift_code' => '',
        'is_choose' => 0,
        'yuyue_num' => 0,
        'new_player_gift_code' => '',
    ];

    public $loginPhone;
    public $sessionLoginName;
    public $channelNum;
    public $channelName;

    public function beforeAction($action, $isNoLayout = 0)
    {
        $path = \Yii::$app->request->getPathInfo();

        $referer = isset($_SERVER['HTTP_REFERER']) ? $_SERVER['HTTP_REFERER'] : '';
        $tmp = parse_url($referer);
        $refererPath = isset($tmp['path']) ? $tmp['path'] : '';

        if ($path) {
            $arr = explode('.', $path);
            if (count($arr) > 0) {
                if (preg_match('/cover(\d+)/', $arr['0'], $match)) {
                    Cms::setSession('channel_num', $match[1]);
                    if ($match[1] < 2 || $match[1] > 50) {
                        throw  new Exception('该页面不存在');
                    }
                }
            }
        }

        if ($refererPath){
            if (preg_match('/cover(\d+)/', $refererPath, $match)) {
                Cms::setSession('channel_num', $match[1]);
                if ($match[1] < 2 || $match[1] > 50) {
                    throw  new Exception('该页面不存在');
                }
            }
        }
        $channelName = Cms::getChannelName();
        $channelName = $channelName ? $channelName : Cms::getSession('channel_name');
        $this->channelName = $channelName;

        $this->channelNum = Cms::getSession('channel_num');
        $this->channelNum = $this->channelNum ? $this->channelNum : 1;
        if (!in_array($this->channelName, ['wapgw', 'pcgw'])) {
            $this->sessionLoginName = 'login_phone'.$this->channelName;
        } else {
            $this->sessionLoginName = $this->channelNum ?  'login_phone'.$this->channelNum : 'login_phone';
        }

        $this->loginPhone = Cms::getSession($this->sessionLoginName);
        return parent::beforeAction($action, $isNoLayout); // TODO: Change the autogenerated stub
    }

    public function actionCover()
    {
        return $this->renderPartial('cover.html');
    }

    public function actionIndex()
    {
        return $this->renderPartial('index.html');
    }

    public function actionError()
    {
        return $this->render('error');
    }

    /**
     * 登录
     */
    public function actionLogin()
    {
        $phone = Cms::getPostValue('phone');
        $res = $this->_loginProcess($this->website_id, $phone, $this->data, $this->sessionLoginName, $this->channelNum, $this->channelName);
        $this->ajaxOutPut($res);
    }

    /**
     * 注销登录
     */
    public function actionLogout()
    {
        $res = Cms::loginProcessLogout($this->sessionLoginName);
        $this->ajaxOutPut($res);
    }

    /**
     * 预约，无需手机验证码
     */
    public function actionYuyue()
    {
//        $res = Cms::loginProcessYuyue($this->website_id, self::GIFT_ID, $this->sessionLoginName, $this->channelNum, $this->channelName);
        $res = $this->_loginProcessYuyue($this->website_id, self::GIFT_ID_NEW_COVER, $this->sessionLoginName, $this->channelNum, $this->channelName);
        if ($res['status'] == 0) {
            $yueyueTotal = YuyueStatModel::getYuyue($this->website_id, 'lszt_total');
            $yueyueTotal = $yueyueTotal['count'];

            $phone = Cms::getSession($this->sessionLoginName);
            $user = UserCenter::getUserInfo($this->website_id, $phone, '', $this->channelNum);
            $userData = UserCenterData::getData($this->website_id, $user['id']);
            $data = $userData['data'];
            $data['yuyue_num'] = $yueyueTotal + 1;
            $data['yuyue_num'] = is_int($data['yuyue_num']/10000)  ? $data['yuyue_num']+1 : $data['yuyue_num'];
            UserCenterData::setData($this->website_id, $user['id'], $data);
            $res['data'] = $data;
        }
        $this->ajaxOutPut($res);
    }

    /**
     * 判断用户是否登录
     */
    public function actionGetUserInfo()
    {
        $res = $this->_loginProcessGetUserInfo($this->website_id, $this->data, $this->sessionLoginName, $this->channelNum, $this->channelName);
        $this->ajaxOutPut($res);
    }

    /**
     * 新老玩家选择
     */
    public function actionChoose()
    {
        $this->_checkLogin();
        $type = Cms::getPostValue('type');
        if (!in_array($type, [1, 2])) {
            $this->ajaxOutPut(['status' => -1, 'msg' => 'type 参数错误']);
        }
        $user = UserCenter::getUserInfo($this->website_id, $this->loginPhone, '', $this->channelNum);
        $userData = UserCenterData::getData($this->website_id, $user['id']);
        $data = $userData ? $userData['data'] : $this->data;

        if (isset($data['new_cover_choose']) && $data['new_cover_choose'] && $data['is_choose'] == 1 && $data['new_player_gift_code']) {
            $this->ajaxOutPut(['status' => -1, 'msg' => '请勿重复选择']);
        }

        if (isset($data['new_cover_choose']) && $data['new_cover_choose'] && $data['is_choose'] == 2 && $data['old_player_gift_code']) {
            $this->ajaxOutPut(['status' => -1, 'msg' => '请勿重复选择']);
        }


        $data['is_choose'] = $type;
        $data['new_cover_choose'] = 1;  // 新 cover 页 可以重新 选择新老用户

        $giftId = '';
        //新用户发礼包
        if ($type == 1) {
            if (!isset($data['new_player_gift_code']) || !$data['new_player_gift_code']) {
//                $res = GiftCode::getUserGiftCode($this->website_id, self::GIFT_ID_NEW_PLAYER, $this->loginPhone);
                $giftId = self::GIFT_ID_NEW_COVER_NEW_PLAYER;
            }
        } else {
            if (!isset($data['old_player_gift_code']) || !$data['old_player_gift_code']) {
                $giftId = self::GIFT_ID_NEW_COVER_OLD_PLAYER;
            }
        }
        if ($giftId) {
            $res = GiftCode::getUserGiftCode($this->website_id, $giftId, $this->loginPhone);
            if (!$res) {
                UserCenterData::setData($this->website_id, $user['id'], $data);
                $this->ajaxOutPut(['status' => 1, 'msg' => '礼包码已经领取完']);
            } else {
                if ($type == 1) {
                    $data['new_player_gift_code'] = $res;
                } else {
                    $data['old_player_gift_code'] = $res;
                }
            }
        }
        UserCenterData::setData($this->website_id, $user['id'], $data);
        $this->ajaxOutPut([
            'status' => 0,
            'msg' => '成功',
            'new_player_gift_code' => $data['new_player_gift_code'],
            'old_player_gift_code' => isset($data['old_player_gift_code']) ? $data['old_player_gift_code'] : '',
        ]);
    }

    /**
     * 检查登录
     */
    private function _checkLogin()
    {
        $res = Cms::loginProcessCheckLogin($this->sessionLoginName);
        if ($res['status'] != 0) {
            $this->ajaxOutPut(['status' => -1, 'msg' => '请登录！']);
        }
    }

    /**
     * 预约获取礼包
     * @param $websiteId
     * @param $giftId   礼包id
     * @param string $sessionLoginName  session 名字
     * @param int $scene    使用场景
     * @param string $channelName 分官网预约数据是否分开统计
     * @return array|mixed|null
     */
    private function _loginProcessYuyue($websiteId, $giftId, $sessionLoginName = 'login_phone', $scene = Cms::YUYUE_SCENE_NEW, $channelName = '')
    {
        $checkLogin = Cms::loginProcessCheckLogin($sessionLoginName);
        if ($checkLogin['status'] != Cms::STATUS_OK) {
            return $checkLogin;
        }
        if (!$websiteId || !$giftId) {
            return ['status' => -1, 'msg' => '参数错误'];
        }
        $loginPhone = Cms::getSession($sessionLoginName);
        $user = UserCenter::getUserInfo($websiteId, $loginPhone, '', $scene);
        $userData = UserCenterData::getData($websiteId, $user['id']);

        $data = isset($userData['data']) ? $userData['data'] : [];

        $isChannel = 0;
        if ($channelName) {
            $channelKey = 'is_yuyue_'.$channelName;
            if (!in_array($channelName, ['wapgw', 'pcgw'])) {
                $isChannel = 1;
            } else {
                $channelName = '';
            }
        }

        if ($isChannel == 1) { //如果是分官网预约数据分开记录
            if (isset($data[$channelKey]) && $data[$channelKey]) {
                return ['status' => -1, 'msg' => '您已经预约，请勿重复预约'];
            }
        } else {
            if ($data['is_yuyue']) {
                return ['status' => -1, 'msg' => '您已经预约，请勿重复预约'];
            }
        }


        $_POST['phone'] = $loginPhone;

        $res = Cms::yuyue(1, $scene, 0, $channelName);
        if ($res['status'] == 0) {
            $res = GiftCode::getUserGiftCode($websiteId, $giftId, $loginPhone);
            if ($isChannel == 1) {
                $data[$channelKey] = 1;
            } else {
                $data['is_yuyue'] = 1;
            }

            if (!$res) {
                UserCenterData::setData($websiteId, $user['id'], $data);
                return ['status' => 1, 'msg' => '礼包码已经领取完'];
            } else {
                $data['gift_code'] = $res;
                $data['new_cover'] = 1; // 属于新  cover 预约
            }
            UserCenterData::setData($websiteId, $user['id'], $data);
            return ['status' => 0, 'msg' => $res];
        }
        if (isset($res['is_repeat']) && $res['is_repeat'] == Cms::GIFT_CODE_REPEAT) {
            if ($isChannel == 1) {
                $data[$channelKey] = 1;
            } else {
                $data['is_yuyue'] = 1;
            }
            UserCenterData::setData($websiteId, $user['id'], $data);
        }
        return $res;
    }

    /**
     * 手机号登录
     * @param $websiteId
     * @param $phone
     * @param array $userData   user_center_data 中 data 数据
     * @param string $sessionLoginName  session 名字
     * @param int $scene    发送验证码使用场景
     * @param string $channelName 分官网预约数据是否分开统计
     * @return array|UserCenter|mixed|null|\yii\db\ActiveRecord
     */
    private function _loginProcess($websiteId, $phone, $userData = [], $sessionLoginName = 'login_phone', $scene = Cms::YUYUE_SCENE_NEW, $channelName = '')
    {
        if (!$phone || !Cms::checkPhone($phone)) {
            return ['status' => -1, 'msg' => '手机号不正确'];
        }
        $res = Cms::checkVerify($scene);    //验证验证码是否正确
        if ($res['status'] != 0) {
            return $res;
        }
        Cms::setSession($sessionLoginName, $phone);
        $user = UserCenter::getUserInfo($websiteId, $phone, '', $scene);
        if (!$user) {
            $user = UserCenter::addUser($websiteId, $phone, '', $scene);
            if (!empty($userData)) {
                UserCenterData::addData($websiteId, $user['id'], $userData);
            }
        }
        $userData = UserCenterData::getData($websiteId, $user['id']);
        $user['data'] = $userData['data'];

        $isChannel = 0;
        if ($channelName) {
            $channelKey = 'is_yuyue_'.$channelName;
            if (!in_array($channelName, ['wapgw', 'pcgw'])) {
                $isChannel = 1;
            }
        }

        //如果是分官网
        if ($isChannel == 1) {
            $user['data']['is_yuyue'] = isset($user['data'][$channelKey]) ? $user['data'][$channelKey] : 0;
        }

        // 新  cover 礼包 重新领取
        $loginPhone = Cms::getSession($this->sessionLoginName);
        $data = isset($userData['data']) ? $userData['data'] : [];
        if (!isset($data['new_cover']) || !$data['new_cover'] || !$data['gift_code']) {
            $res = GiftCode::getUserGiftCode($this->website_id, self::GIFT_ID_NEW_COVER, $loginPhone);
            if (!$res) {    // 礼包码已经领取完
            } else {
                $data['gift_code'] = $res;
                UserCenterData::setData($this->website_id, $user['id'], $data);
                $user['data']['gift_code'] = $res;
            }
        }

        // 新 cover 页 新老用户重新领取
        if (!isset($user['data']['new_cover_choose']) || !$user['data']['new_cover_choose']) {
            $user['data']['is_choose'] = 0;
            $user['data']['new_player_gift_code'] = '';
            $user['data']['old_player_gift_code'] = '';
        }
        return ['status' => 0, 'msg' => $user];
    }

    /**
     * 获取登录用户信息
     * @param $websiteId
     * @param array $userData   user_center_data 中 data的数据
     * @param string $sessionLoginName session 名字
     * @param string $channelName  分官网预约数据是否分开统计
     * @return array
     */
    private function _loginProcessGetUserInfo($websiteId, $userData = [], $sessionLoginName = 'login_phone', $scene = '', $channelName = '')
    {
        $checkLogin = Cms::loginProcessCheckLogin($sessionLoginName);
        if ($checkLogin['status'] != Cms::STATUS_OK) {
            return $checkLogin;
        }
        $loginPhone = Cms::getSession($sessionLoginName);
        $user = UserCenter::getUserInfo($websiteId, $loginPhone, '', $scene);
        $data = UserCenterData::getData($websiteId, $user['id']);

        $isChannel = 0;
        if ($channelName) {
            $channelKey = 'is_yuyue_'.$channelName;
            if (!in_array($channelName, ['wapgw', 'pcgw'])) {
                $isChannel = 1;
            }
        }

        if (!$data) {
            $user['data'] = $userData;
        } else {
            $user['data'] = $data['data'];
        }
        //如果是分官网
        if ($isChannel == 1) {
            $user['data']['is_yuyue'] = isset($user['data'][$channelKey]) ? $user['data'][$channelKey] : 0;
        }

        // 新 cover 页 新老用户重新领取
        if (!isset($user['data']['new_cover_choose']) || !$user['data']['new_cover_choose']) {
            $user['data']['is_choose'] = 0;
            $user['data']['new_player_gift_code'] = '';
            $user['data']['old_player_gift_code'] = '';
        }
        return ['status' => 0, 'msg' => $user];
    }
}
