<?php
/**
 * 寻找锦鲤
 */
namespace app\controllers\sm;


use common\Cms;
use common\components\H5BaseController;
use common\models\GiftCode;
use common\models\h5\H5UserCenter;
use common\models\h5\H5UserCenterData;
use common\models\h5\sm\Team;
use common\models\h5\sm\TeamMember;
use common\models\UserCenter;
use common\models\UserCenterData;
use yii\helpers\Json;

class JinliController extends H5BaseController
{

    const LOGIN_GIFT_ID=430;//登陆奖励
    const TOP_5_GIFT_ID = 431;//加入5人奖励
    const TOP_10_GIFT_ID=432;//加入10人奖励
    const TOP_50_GIFT_ID = 433;//加入50人奖励
    const TOP_100_GIFT_ID = 434;//加入100人奖励
    const TOP_SCHOOL_1_ID = 435;//学校排名第一奖励
    const TOP_CITY_1_ID = 436;//本市第一奖励
    const TOP_PROVINCE_1_ID= 437;//省第一奖励
    const TOP_PROVINCE_2_ID=438;//省第二奖励
    const TOP_PROVINCE_3_ID=439;//省第三奖励

    const TYPE_FIRST_LOGIN = 1;//登陆奖励
    const TYPE_TOP_5 = 5;//团队人数超过5人
    const TYPE_TOP_10 = 10;//团队人数超过10人
    const TYPE_TOP_50 = 50;//团队人数超过50人
    const TYPE_TOP_100 = 100;//团队人数超过100人
    const TYPE_SCHOOL_1 = 2;//本地排行第一
    const TYPE_CITY_1 = 3;//市排行第一
    const TYPE_PROVINCE_1 = 7;//省排行第一
    const TYPE_PROVINCE_2 = 8;//省排行第二
    const TYPE_PROVINCE_3 = 9;//省排行第三
    const TYPE_STARS = 999;//锦鲤奖

    const START_AT = 1546272000;//开始时间1月1日
    const END_AT =1553011200;//结束时间3月20日
    const STARS_CREATE_AT = 1549296000;//锦鲤弹出时间2-5
    const TOP_LOCK_AT =1550592000;//榜单锁定时间2月20
    const TOP_SHOW_AT = 1550851200;//榜单奖励展示时间2月23日开始

    private $myTeam;

    public function beforeAction($action)
    {
        if(self::END_AT<time()){
            $this->echoJson(9014);
        }
        $this->user=$user = Cms::getSession('h5_user');
        $info = $user?$user['info']:[];
        $this->myTeam = isset($info['data']['team'])?$info['data']['team']:[];
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    /**
     * 登陆
     */
    public function actionLogin()
    {
        $isCaptain=false;
        $phone = Cms::getPostValue('phone');
        $nickname = Cms::getPostValue('nickname');
        $lat = Cms::getPostValue('lat');
        $lng = Cms::getPostValue('lng');
        $res = Cms::checkVerify(null);    //验证验证码是否正确
        if ($res['status'] != 0) {
            $this->echoJson(6);
        }
        if(!$nickname){
            $this->echoJson(2);
        }
        $user = H5UserCenter::getUserInfo($this->h5Id, $phone, '');
        if (!$user || empty($user)) {
            $user = H5UserCenter::addUser($this->h5Id, $phone, '');
            $info=['nickname'=>$nickname,'lat'=>$lat,'lng'=>$lng];
            $user['info']['data']=$info;
            H5UserCenterData::addData($this->h5Id, $user['id'], $info);
        }else{
            $user['info'] = H5UserCenterData::getData($this->h5Id,$user['id']);
            $user['info']['data']['lat']=$lat;
            $user['info']['data']['lng'] = $lng;
            H5UserCenterData::setUserInfo($this->h5Id,$user['id'], $user['info']['data']);
        }
            //data信息
        $this->myTeam = isset($user['info']['data']['team'])?$user['info']['data']['team']:[];
        if($this->myTeam){
            foreach ($this->myTeam as $t){
                if($t['is_captain']){
                    $isCaptain = true;
                    break;
                }
            }
        }
        $this->user = $user;
        Cms::setSession('h5_user_id', $user['id']);
        Cms::setSession('h5_user', $user);
        $gift = $this->_getGift();
        $this->echoJson(0,'',['user'=>$user,'gift'=>$gift,'is_captain'=>$isCaptain]);

    }

    private function _getGift(){
        $gift=[];
        $captainTeamId=0;
        //第一登陆礼包
        list($code,$isLoginGift)= GiftCode::getGiftCodeByPhone($this->websiteId,self::LOGIN_GIFT_ID,$this->user['phone'],true,0,$this->user['phone']);
        if(!$isLoginGift){
            $gift[]= ['type'=>self::TYPE_FIRST_LOGIN,'code'=>$code];
        }
        foreach ($this->myTeam as $teamId=>$m){
            if($m['is_captain'])
                $captainTeamId=$teamId;
        }
        if($captainTeamId){
            $captainTeam = Team::getTeamInfo($this->websiteId,$this->h5Id,$captainTeamId);
            if($captainTeam['num']>=5){
                //top5
                list($code,$isTop5Gift)= GiftCode::getGiftCodeByPhone($this->websiteId,self::TOP_5_GIFT_ID,$this->user['phone'],true,0,$this->user['phone']);
                if(!$isTop5Gift){
                    $gift[]= ['type'=>self::TYPE_TOP_5,'code'=>$code];
                }
            }
            if($captainTeam['num']>=10) {
                //top10
                list($code,$isTop10Gift) = GiftCode::getGiftCodeByPhone($this->websiteId, self::TOP_10_GIFT_ID, $this->user['phone'],true,0,$this->user['phone']);
                if (!$isTop10Gift) {
                    $gift[]= ['type'=>self::TYPE_TOP_10,'code'=>$code];
                }
            }
            if($captainTeam['num']>=50) {
                //top50
                list($code,$isTop50Gift) = GiftCode::getGiftCodeByPhone($this->websiteId, self::TOP_50_GIFT_ID, $this->user['phone'],true,0,$this->user['phone']);
                if (!$isTop50Gift) {
                    $gift[]= ['type'=>self::TYPE_TOP_50,'code'=>$code];
                }
            }
            if($captainTeam['num']>=100) {
                //top100
                list($code,$isTop100Gift) = GiftCode::getGiftCodeByPhone($this->websiteId, self::TOP_100_GIFT_ID, $this->user['phone'],true,0,$this->user['phone']);
                if (!$isTop100Gift) {
                    $gift[]= ['type'=>self::TYPE_TOP_100,'code'=>$code];
                }
            }
        }
        //排行榜
        if(self::TOP_SHOW_AT<time()){

            foreach ($this->myTeam as $t){
                //是否榜单固化前加入
                $memberInfo = TeamMember::getInfo($this->websiteId,$this->h5Id,$t['id'],$this->user['id']);
                if($memberInfo && $memberInfo['created_at']<=self::TOP_LOCK_AT){
                    //本地第一
                    $teamInfo = Team::getTeamInfo($this->websiteId,$this->h5Id,$t['id']);
                    $schoolTotal = Team::getTotal($this->websiteId,$this->h5Id,Team::TYPE_TOP_SCHOOL,$t['school_lbs_uid']);
                    if($teamInfo['school_top']==1 && $schoolTotal>5 && !TeamMember::isTeamSchoolTop1Gift($this->websiteId,$this->h5Id,$t['id'],$this->user['id'])){
                        list($code,$school1GiftLogId) = GiftCode::getGiftCodeByPhone($this->websiteId, self::TOP_SCHOOL_1_ID, $this->user['phone'],false,0,$this->user['phone']);
                        if ($code) {
                            TeamMember::setTeamSchoolTop1Gift($this->websiteId,$this->h5Id,$t['id'],$this->user['id']);
                            $gift[]= ['type'=>self::TYPE_SCHOOL_1,'code'=>$code];
                        }
                    }
                    //本市第一
                    $cityTotal = Team::getTotal($this->websiteId,$this->h5Id,Team::TYPE_TOP_CITY,$t['city']);
                    if($teamInfo['city_top']==1 && $cityTotal>9 && !TeamMember::isTeamCityTop1Gift($this->websiteId,$this->h5Id,$t['id'],$this->user['id'])){
                        list($code,$city1GiftLogId) = GiftCode::getGiftCodeByPhone($this->websiteId, self::TOP_CITY_1_ID, $this->user['phone'],false,0,$this->user['phone']);
                        if ($code) {
                            TeamMember::setTeamCityTop1Gift($this->websiteId,$this->h5Id,$t['id'],$this->user['id']);
                            $gift[]= ['type'=>self::TYPE_CITY_1,'code'=>$code];
                        }
                    }
                    //省排名
                    $provinceTotal = Team::getTotal($this->websiteId,$this->h5Id,Team::TYPE_TOP_PROVINCE,$t['province']);
                    if($teamInfo['province_top']==1 && $provinceTotal>30 && !TeamMember::isTeamProvinceTop1Gift($this->websiteId,$this->h5Id,$t['id'],$this->user['id'])){
                        list($code,$province1GiftLogId) = GiftCode::getGiftCodeByPhone($this->websiteId, self::TOP_PROVINCE_1_ID, $this->user['phone'],false,0,$this->user['phone']);
                        if ($code) {
                            TeamMember::setTeamProvinceTop1Gift($this->websiteId,$this->h5Id,$t['id'],$this->user['id']);
                            $gift[]= ['type'=>self::TYPE_PROVINCE_1,'code'=>$code];
                        }
                    }
                    if($teamInfo['province_top']==2 && $provinceTotal>30 && !TeamMember::isTeamProvinceTop2Gift($this->websiteId,$this->h5Id,$t['id'],$this->user['id'])){
                        list($code,$province2GiftLogId) = GiftCode::getGiftCodeByPhone($this->websiteId, self::TOP_PROVINCE_2_ID, $this->user['phone'],false,0,$this->user['phone']);
                        if ($code) {
                            TeamMember::setTeamProvinceTop2Gift($this->websiteId,$this->h5Id,$t['id'],$this->user['id']);
                            $gift[]= ['type'=>self::TYPE_PROVINCE_2,'code'=>$code];
                        }
                    }
                    if($teamInfo['province_top']==3 && $provinceTotal>30 && !TeamMember::isTeamProvinceTop3Gift($this->websiteId,$this->h5Id,$t['id'],$this->user['id'])){
                        list($code,$province3GiftLogId) = GiftCode::getGiftCodeByPhone($this->websiteId, self::TOP_PROVINCE_3_ID, $this->user['phone'],false,0,$this->user['phone']);
                        if ($code) {
                            TeamMember::setTeamProvinceTop3Gift($this->websiteId,$this->h5Id,$t['id'],$this->user['id']);
                            $gift[]= ['type'=>self::TYPE_PROVINCE_3,'code'=>$code];
                        }
                    }
                }
            }
        }

        //锦鲤奖
        if(self::STARS_CREATE_AT<time()) {
            $uid = Team::getJinliUid($this->websiteId,$this->h5Id);
            if ($uid &&  !Team::isAlertJinli($this->website_id,$this->h5Id, $this->user['id'])) {
                    if ($uid == $this->user['id']) {
                        $gift[] = ['type' => self::TYPE_STARS, 'is_owner' => true, 'nickname' => isset($this->user['info']['data']['nickname']) ?
                            $this->user['phone'].$this->user['info']['data']['nickname'] : ''];
                    } else {
                        $userData = H5UserCenterData::getData($this->h5Id, $uid);
                        $userInfo = H5UserCenter::find()->where(['id'=>$uid])->asArray()->one();
                        $gift[] = ['type' => self::TYPE_STARS, 'is_owner' => false, 'nickname' => $userInfo&& isset($userData['data']) ? substr_replace($userInfo['phone'], '****', 3, 4).'['.$userData['data']['nickname'].']' : ''];
                    }

                if ($gift) {
                    if($uid != $this->user['id'])
                        Team::setAlertJinli($this->website_id,$this->h5Id, $this->user['id']);
                }
            }
        }
        return $gift;
    }

    public function actionJinliInfo(){
        $code = 9009;
        $uid = Team::getJinliUid($this->website_id,$this->h5Id);
        if($this->user['id']==$uid){
            $code=0;
            if(\Yii::$app->request->isAjax){
                $info['name'] = Cms::getPostValue('name');
                $info['serverId'] = Cms::getPostValue('server_id');
                $info['roleId'] = Cms::getPostValue('role_id');
                $info['phone'] = Cms::getPostValue('phone');
                $info['qq'] = Cms::getPostValue('qq');
                $info['wechat'] = Cms::getPostValue('wechat');
                $info['sPhone'] = Cms::getPostValue('s_phone');
                H5UserCenterData::addData($this->h5Id, $this->user['id'], $info);
                Team::setAlertJinli($this->website_id,$this->h5Id, $this->user['id']);
            }
        }
        $this->echoJson($code);
    }

    /**
     * 通过手机号码获取昵称
     */
    public function actionCheckUser(){
        $phone = Cms::getPostValue('phone');
        $user = H5UserCenter::getUserInfo($this->h5Id, $phone, null);
        $data = H5UserCenterData::getData($this->h5Id, $user['id']);
        $code= $user?0:9001;
        $this->echoJson($code,'',['nickname'=>isset($data['data']['nickname'])?$data['data']['nickname']:'']);
    }


    /**
     * 我的战队
     */
    public function actionMyTeam(){
        $team=[];
        foreach ($this->myTeam as $t){
            $team[]=$t;
        }
        $this->echoJson(0,'',$team);
    }

    /**
     * 获取排行
     */
    public function actionGetTop(){
        $type = Cms::getPostValue('type',0);
        $schoolLbsUid = Cms::getPostValue('name');
        $list = Team::getTop($this->websiteId,$this->h5Id,$type,$schoolLbsUid);
        $this->echoJson(0,'',$list);
    }

    /**
     * 战队信息
     */
    public function actionTeamInfo(){
        $teamId = Cms::getPostValue('team_id');
        $info = Team::getTeamInfo($this->websiteId,$this->h5Id,$teamId);
        if($info){
            $member = TeamMember::getTeamMember($this->websiteId,$this->h5Id,$teamId);
            $info['is_captain'] = isset($this->myTeam[$teamId])&&$this->myTeam[$teamId]['is_captain']?true:false;
            $info['is_member'] = isset($this->myTeam[$teamId])?true:false;
            $info['member'] = $member;
            $info['school_total'] = Team::getTotal($this->websiteId,$this->h5Id,Team::TYPE_TOP_SCHOOL,$info['school_lbs_uid']);
            $info['city_total'] = Team::getTotal($this->websiteId,$this->h5Id,Team::TYPE_TOP_CITY,$info['city']);
            $info['province_total'] = Team::getTotal($this->websiteId,$this->h5Id,Team::TYPE_TOP_PROVINCE,$info['province']);
        }

        $this->echoJson(0,'',$info);
    }


    /**
     * 获取学校战队
     */
    public function actionGetSchoolTeam(){
        $lbsUid = Cms::getPostValue('lbs_uid');
        $teamList = Team::getTeamListBySchool($this->websiteId,$this->h5Id,$lbsUid);
        foreach ($teamList as &$t){
            if(isset($this->myTeam[$t['id']])){
                $t['is_myTeam'] = true;
                $t['is_captain'] = $this->myTeam[$t['id']]['is_captain'];
            }else{
                $t['is_myTeam'] = false;
                $t['is_captain'] = false;
            }
        }
        $this->echoJson(0,'',$teamList);
    }

    /**
     * 加入战队
     */
    public function actionJoinTeam(){
        $code = 9002;
        $res = false;
        $teamId = intval(Cms::getPostValue('team_id'));

        if(!Team::isTodayJoin($this->websiteId,$this->h5Id,$this->user['id'])){
            if(TeamMember::getTodayAddCount($this->websiteId,$teamId,$this->h5Id)>=30){
                $code=9005;//当日队伍加入人数不超过20
            }else{
                //当前用户不能超过5个队伍
                if(count($this->myTeam)>=5){
                    $code=9006;
                }else{
                    $teamInfo = Team::getTeamInfo($this->websiteId,$this->h5Id,$teamId);
                    $distance = Team::getDistance($this->user['info']['data']['lat'],$this->user['info']['data']['lng'],$teamInfo['school_lat'],$teamInfo['school_lng']);

                    if($teamInfo && $distance<=5000 && $this->user['id']){
                        $res = TeamMember::join($this->websiteId,$this->h5Id,$teamId,$this->user['id'],0,$this->user['info']['data']['nickname'],self::TOP_LOCK_AT);
                    }else{
                        $code=9007;
                    }
                    if($res){
                        Team::setTodayJoin($this->websiteId,$this->h5Id,$this->user['id']);
                        //更新userdata
                        $code = 0;
                        $teamInfo['is_captain'] = false;
                        $this->user['info']['data']['team'][$teamId] = $teamInfo;
                        Cms::setSession('h5_user', $this->user);
                        H5UserCenterData::setUserInfo($this->h5Id, $this->user['id'], $this->user['info']['data']);
                    }

                }

            }
        }else{
            $code = 9011;
        }


        $this->echoJson($code);
    }


    /**
     *创建战队
     */
    public function actionCreateTeam(){
        $code = 9003;
        $data=[];
        $isCaptain = false;
        if(count($this->myTeam)>=5){
            $code = 9004;
        }else{
            if($this->myTeam){
                foreach ($this->myTeam as $t){
                    if($t['is_captain']){
                        $isCaptain = true;
                        break;
                    }
                }
            }
            if(!$isCaptain){
                $teamName = Cms::getPostValue('team_name');
                $schoolName = Cms::getPostValue('school_name');
                $schoolLbsUid = Cms::getPostValue('school_lbs_uid');
                $schoolLat = Cms::getPostValue('school_lat');
                $schoolLng = Cms::getPostValue('school_lng');
                $city = Cms::getPostValue('city');
                $province = Cms::getPostValue('province');
                if(!$city && (strpos($province,'北京')!==false||strpos($province,'重庆')!==false
                    ||strpos($province,'天津')!==false||strpos($province,'上海')!==false)){
                    $city = $province;
                }
                if(!$city || !$province ||!$this->user['id'] || !$schoolLat || !$schoolLat || !$schoolLbsUid){
                    $code = 9010;
                }else{
                    $data = ['name'=>$teamName,'school_name'=>$schoolName,'school_lbs_uid'=>$schoolLbsUid,'school_lat'=>$schoolLat,
                        'school_lng'=>$schoolLng,'city'=>$city,'province'=>$province,'created_uid'=>$this->user['id'],'created_uid'=>$this->user['id']];
                    $teamId = Team::createTeam($this->websiteId,$this->h5Id,$data,self::TOP_LOCK_AT,$this->user['info']['data']['nickname']);
                    if($teamId){
                        $code=0;
                        //更新userdata
                        $teamInfo = Team::getTeamInfo($this->websiteId,$this->h5Id,$teamId);
                        $teamInfo['is_captain'] = 1;
                        $this->user['info']['data']['team'][$teamId] = $teamInfo;
                        Cms::setSession('h5_user', $this->user);
                        H5UserCenterData::setUserInfo($this->h5Id, $this->user['id'], $this->user['info']['data']);
                        $data['team_id'] = $teamId;
                    }
                }
            }else{
                $code=9013;
            }


        }

        $this->echoJson($code,'',$data);
    }

    /**
     * 我的礼包
     */
    public function actionMyGift(){
        $list = GiftCode::getGiftCodeLogGroup($this->websiteId,$this->user['phone'],$this->user['phone']);
        foreach ($list as &$l){
            switch ($l['gift_id']){
                case self::TOP_5_GIFT_ID:
                    $l['type']=self::TYPE_TOP_5;
                    $l['type_name'] = '探险队达5人';
                    break;
                case self::TOP_10_GIFT_ID:
                    $l['type']=self::TYPE_TOP_10;
                    $l['type_name'] = '探险队达10人';
                    break;
                case self::TOP_50_GIFT_ID:
                    $l['type']=self::TYPE_TOP_50;
                    $l['type_name'] = '探险队达50人';
                    break;
                case self::TOP_100_GIFT_ID:
                    $l['type']=self::TYPE_TOP_100;
                    $l['type_name'] = '探险队达100人';
                    break;
                case self::TOP_SCHOOL_1_ID:
                    $l['type']=self::TYPE_SCHOOL_1;
                    $l['type_name'] = '全校第1名';
                    break;
                case self::TOP_CITY_1_ID:
                    $l['type']=self::TYPE_CITY_1;
                    $l['type_name'] = '全市第1名';
                    break;
                case self::TOP_PROVINCE_1_ID:
                    $l['type']=self::TYPE_PROVINCE_1;
                    $l['type_name'] = '全省第1名';
                    break;
                case self::TOP_PROVINCE_2_ID:
                    $l['type']=self::TYPE_PROVINCE_2;
                    $l['type_name'] = '全省第2名';
                    break;
                case self::TOP_PROVINCE_3_ID:
                    $l['type']=self::TYPE_PROVINCE_3;
                    $l['type_name'] = '全省第3名';
                    break;
                case self::LOGIN_GIFT_ID:
                default:
                    $l['type']=self::TYPE_TOP_10;
                    $l['type_name'] = '登陆有奖';
                    break;
            }

        }
        $this->echoJson(0,'',$list);
    }


    public function actionJinliAlert(){
        $code = 9012;
        $data=[];
        if(self::STARS_CREATE_AT<time()) {
            $code = 0;
            $uid = Team::getJinliUid($this->websiteId, $this->h5Id);
            if($uid){
                $userInfo = H5UserCenter::find()->where(['id'=>$uid])->asArray()->one();
                $userData = H5UserCenterData::getData($this->h5Id, $uid);
                $data['nickname'] = $userInfo&& $userData&&isset($userData['data']['nickname'])?substr_replace($userInfo['phone'], '****', 3, 4).'['.$userData['data']['nickname'].']':'';

            }
            }
        $this->echoJson($code,'',$data);
    }
    


}