<?php

namespace app\controllers\nba;

use common\cache\h5\H5UserCache;
use common\Cms;
use common\components\H5BaseController;
use common\components\HomeController;
use common\components\MailUtils;
use common\helpers\Utils;
use common\models\GiftCode;
use common\models\h5\H5User;
use yii\helpers\Json;

/**
 * Created by PhpStorm.
 * User: lin.zhou
 * Date: 2018/7/31
 * Time: 11:28
 */
class PsqController extends H5BaseController
{
    const SECRET_KEY_ANDROID = 'eiaXIeRdDCO34gH6&P2IY7UWQzzALFK&ZQxhgpWk#3ihN4$E5kXeQA1Ix9AAL7odmfKf%$bCMHnW65dars$TqjrJSQ^owv3e3w&xV';
    const SECRET_KEY_IOS = 'Ce@m6In63Xiegz*Wy@3DPVK@AZ^acpC3mi%0oAL2IcEk!pqqVl*TC%jU1L7y5Jgm^dx$oUStncMgntpHlwAA0pVZKtrypEJ^u9Gw';
    const API_URL_ANDROID = 'https://nba-api-prod-and.nmc.popcap.com.cn/g/outchannel/getUserInfo';
    const API_URL_IOS = 'https://nba-api-prod-ios.nmc.popcap.com.cn/g/outchannel/getUserInfo';

    public function beforeAction($action)
    {
        echo "";exit;   // 2018-10-10 下线
        Cms::setSession('h5_id', 14);
        Cms::setSession('h5_website_id', 85);
        Cms::setSession('sms_h5_website_id', 85);
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionLogin()
    {
        $this->_checkWxLogin();
        $roleId = Cms::getPostValue('roleId');
        $roleName = Cms::getPostValue('roleName');
        $serverIds = Cms::getPostValue('serverIds');
        $phone = Cms::getPostValue('phone');

        if (!is_numeric($roleId)) {
            $this->ajaxOutPut(['status' => -1, 'msg' => '游戏id只能是数字']);
        }
        if (!in_array($serverIds, [200, 201])) {
            $this->ajaxOutPut(['status' => -1, 'msg' => '游戏区服不正确']);
        }
        if (!$phone || !Cms::checkPhone($phone)) {
            $this->ajaxOutPut(['status' => -1, 'msg' => '手机号不正确']);
        }
        $roleId = (int)$roleId;
        if (!$roleId) {
            $this->ajaxOutPut(['status' => -1, 'msg' => '游戏id不正确']);
        }
        $res = Cms::checkVerify(Cms::YUYUE_SCENE_OLD);
        if ($res['status'] != 0) {
            //@todo 测试暂时开放
            $this->ajaxOutPut($res);
        }

        $params = [
            'serverIds' => $serverIds,
            'roleId' => $roleId,
            'roleName' => $roleName,
        ];
        $checkApi = $this->_checkUserApi($params);
        if (!$checkApi) {
            $this->ajaxOutPut(['status' => -1, 'msg' => '该用户不存在']);
        }
        if ($checkApi != 1) {
            $this->ajaxOutPut(['status' => -1, 'msg' => '接口异常，请稍后重试！']);
        }

        $h5WebsiteId = Cms::getSession('h5_website_id');
        $h5Id = Cms::getSession('h5_id');

        $time = time();
        Cms::setSession('psq_login_time', $time);

        $user = H5User::getUserInfo($h5WebsiteId, $h5Id, $phone);
        if (!$user) {
            $data = [];
        } else {
            $data = $user['data'];
        }
        $data[$time] = [
            'userInfo' => [
                'roleId' => $roleId,
                'roleName' => $roleName,
                'serverIds' => $serverIds,
            ]
        ];

        $params = [
            'phone' => $phone,
            'data' => $data,
        ];

        H5User::setUserInfo($h5WebsiteId, $h5Id, $phone, $params);

        Cms::setSession('h5_psq_user_phone', $phone);
        $userDetail = isset($data['userDetail']) ? $data['userDetail'] : [];
        $this->ajaxOutPut(['status' => 0, 'msg' => '成功', 'userDetail' => $userDetail]);
    }

    private function _generateSign($params, $type = 'android')
    {
        ksort($params);
        $sign = '';
        foreach ($params as $k => $v) {
            $sign .= '&'.$k.'='.$v;
        }
        $secretKey = ($type == 'android') ? self::SECRET_KEY_ANDROID : self::SECRET_KEY_IOS;
        $sign .= $secretKey;

        $sign = sha1($sign);
        return $sign;
    }

    private function _checkWxLogin()
    {
        $h5WebsiteId = Cms::getSession('h5_website_id');
        $h5Id = Cms::getSession('h5_id');

        if (!$h5Id || !$h5WebsiteId) {
            $this->ajaxOutPut(['status' => 1, 'msg' => '登录失败，请退出重新登录']);
        }
    }

    /**
     * 获取礼包码
     */
    public function actionGetGift()
    {
        $options = Cms::getPostValue('options');
        if (!$options || empty($options)) {
            $this->ajaxOutPut(['status' => -1, 'msg' => '选项参数错误']);
        }
        $h5WebsiteId = Cms::getSession('h5_website_id');
        $h5Id = Cms::getSession('h5_id');
        $phone = Cms::getSession('h5_psq_user_phone');
        $loginTime = Cms::getSession('psq_login_time');
        if (!$phone) {
            $this->ajaxOutPut(['status' => -1, 'msg' => '登录失败，请退出重新登录']);
        }

        $user = H5User::getUserInfo($h5WebsiteId, $h5Id, $phone);
        $data = $user['data'];
        $data[$loginTime]['userOptons'] = $options;

        H5User::setUserInfo($h5WebsiteId, $h5Id, $phone, ['data' => $data]);


//        $res = Cms::getGiftNoYzm($phone, 343);

        $res = GiftCode::getUserGiftCode($this->website_id, 343, $phone, '');

        if (!$res) {
            $this->ajaxOutPut(['status' => -1, 'msg' => '礼包码已经领取完']);
        }
        $this->ajaxOutPut(['status' => 0, 'msg' => $res]);

    }

    /**
     * 填写详细信息
     */
    public function actionSaveDetail()
    {
        $h5WebsiteId = Cms::getSession('h5_website_id');
        $h5Id = Cms::getSession('h5_id');
        $phone = Cms::getSession('h5_psq_user_phone');

        if (!$phone) {
            $this->ajaxOutPut(['status' => -1, 'msg' => '登录失败，请退出重新登录']);
        }

        $user = H5User::getUserInfo($h5WebsiteId, $h5Id, $phone);
        if (!isset($user['data']['userDetail'])) {
            $name = Cms::getPostValue('name');
            $qq = Cms::getPostValue('qq');
            $address = Cms::getPostValue('address');
            $user['data']['userDetail'] = [
                'name' => $name,
                'qq' => $qq,
                'address' => $address,
            ];
            H5User::setUserInfo($h5WebsiteId, $h5Id, $phone, ['data' => $user['data']]);
            $this->ajaxOutPut(['status' => 0, 'msg' => '成功']);
        }
        $this->ajaxOutPut(['status' => -1, 'msg' => '您已经填写，请勿重复填写']);
    }

    /**
     * 检查用户是否存在
     * @param $params
     * @return bool
     */
    private function _checkUserApi($params)
    {
        $type = $params['serverIds'] == 200 ? 'android' : 'ios';
        $sign = $this->_generateSign($params, $type);
        $params['signature'] = $sign;
        $url = $params['serverIds'] == 200 ? self::API_URL_ANDROID : self::API_URL_IOS;
        $result = Utils::sendHttpRequestJson($url, $params);
        if (!isset($result['info']) || !isset($result['info']['http_code']) || $result['info']['http_code'] != 200) {
            $mailList=['lin.zhou@yingxiong.com' => 'zhou.lin','hui.liu@yingxiong.com' => 'hui.liu', 'gang.zhang@yingxiong.com' => 'zhang.gang',
                'ling.wang@yingxiong.com' => 'ling.wang'];
            MailUtils::sendMail('nba h5 获取角色接口异常', json_encode($result), $mailList);
            return -1;
        }
        if (isset($result['content']) && $result['content']) {
            $content = Json::decode($result['content'], true);
            if (isset($content['data']) && !empty($content['data'])) {
                return true;
            }
        }
        return false;
    }
}