<?php
/**
 * 首页
 *
 * @author Administrator
 *
 */

namespace app\controllers;


use common\components\PcController;
use common\Cms;
use common\widgets\commonMethod\CommonMethodController;
use yii\helpers\Url;

class SiteController extends PcController
{
    public function beforeAction($action)
    {
        return parent::beforeAction($action, 1); // TODO: Change the autogenerated stub
    }

    public function actionCover()
    {
        return $this->render('cover');
    }

    public function actionIndex()
    {
        $this->layout = false;
        $testType = Cms::getGetValue('testType', 0);
        $data = array();
        $index_video = $this->getRecommend('index_video', 1);   //首页推广视频
        $data['index_video'] = $index_video[0];

        $index_banner = $this->getRecommend('index_banner');   //首页banner
        $data['index_banner'] = $index_banner;

        $data['zuixin'] = $this->getContentArr(75, 10);    //最新
        $data['xinwen'] = $this->getContentArr(76, 10);    //新闻
        $data['gonggao'] = $this->getContentArr(77, 10);    //公告
        $data['huodong'] = $this->getContentArr(78, 10);    //活动
        $data['gonglue'] = $this->getContentArr(79, 10);    //攻略

        $data['wujiang'] = $this->getContentArr(81, 1000);    //武将
        $data['yongbing'] = $this->getContentArr(82, 1000);    //佣兵
        $data['daoju'] = $this->getContentArr(83, 1000);    //道具
        $data['fenlei'] = $this->getContentArr(84, 1000);    //分类

        $data['ditu'] = $this->getContentArr(85, 1000);    //地图
        $data['jietu'] = $this->getContentArr(86, 1000);    //截图

        $data['video'] = $this->getContentArr(87, 1000);    //视频

        $data['partner'] = $this->getRecommend('partner', 100);   //合作方
        if ($testType == 1) {
            pr($data, 1);
        }
        return $this->renderPartial('index.html', $data);
    }

    public function actionError()
    {
        return $this->render('error');
    }

    public function actionTest($type = '', $id = '')
    {
        if (!$type) {
            echo '不存在';exit;
        }
        $_GET['testType'] = 1;
        $action = 'action'.$type;
        $id = Cms::getGetValue('id', 0);
        if ($id) {
            $this->$action($id);
        } else {
            $this->$action();
        }

    }
}
