<?php
/**
 * Created by PhpStorm.
 * User: lin.zhou
 * Date: 2018/10/13 0013
 * Time: 10:58
 */

namespace app\controllers\dfzj;


use common\Cms;
use common\components\H5BaseController;
use common\models\GiftCode;
use common\models\h5\dfzj\H5DfzjInvHurtLog;
use common\models\h5\dfzj\H5DfzjInvUsersLog;
use common\models\h5\H5UserCenter;
use common\models\h5\H5UserCenterData;

class InvController extends H5BaseController
{
    public $data = [
//        'invUsers' => [],   // 邀请人
        'num' => [  // 可进攻次数
            'day' => '2018-10-13',  // 时间
            'useNum' => 0,  // 当天已使用次数
            'getNum' => 0,  // 当天已经获取的进攻次数
        ],
//        'hurtLog' => [
////            [
////                'time' => 0,    // 进攻时间
////                'hurt' => 0,    // 伤害量
////            ],
//        ],

        'attackTarget' => [ // 攻击目标
            1 => [
                'totalBlood' => 20000,
                'useBlood' => 0,
            ],
            2 => [
                'totalBlood' => 20000,
                'useBlood' => 0,
            ],
            3 => [
                'totalBlood' => 20000,
                'useBlood' => 0,
            ],
            4 => [
                'totalBlood' => 50000,
                'useBlood' => 0,
            ],
         ],
        'giftCodeLog' => [ // 礼包码 log
//            '385' => 'sss',
        ],
    ];

    // 击破防线礼包
    public $giftIdsAttack = [
        1 => 385,
        2 => 386,
        3 => 387,
        4 => 388,
    ];

    // 邀请人数礼包
    public $giftIdsInv = [
        1 => 380,
        2 => 381,
        3 => 382,
        4 => 383,
        5 => 384,
    ];

    /**
     * 邀请礼包需要邀请的人数
     * @var array
     */
    public $giftIdsInvCondition = [
        1 => 100,
        2 => 200,
        3 => 300,
        4 => 500,
        5 => 1000,
    ];

    public function beforeAction($action)
    {
        if (time() > strtotime("2018-11-01 23:00:00")) {
            $this->echoJson(6013);
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    /**
     * 获取用户详情
     */
    public function actionGetUserInfo()
    {
        $inviteCode = Cms::getPostValue('invite_code');
        if ($inviteCode) {
            // 验证邀请码是否正确
            $invUser = $this->_checkInviteUser($inviteCode);
            $userId = $invUser['id'];
            $data = H5UserCenterData::getData($this->h5Id, $userId);
            $userData['nickname'] = $data['data']['nickname'];
        } else {
            list($userData, $countInvUsers) = $this->_getH5Data();
            $userId = $this->user['id'];
            $userData['hurtLogs'] = H5DfzjInvHurtLog::getLog($this->websiteId, $this->h5Id, $this->user['id']);
            if ($userData['hurtLogs'] && !empty($userData['hurtLogs'])) {
                foreach ($userData['hurtLogs'] as &$v) {
                    $v['created_at'] = date('m/d H:i', $v['created_at']);
                }
            }
        }
        $userData['invLogs'] = $this->_getInvUsersLog($userId);
        $this->echoJson(0, '', $userData);
    }

    public function _getH5Data()
    {
        $userData = parent::_getH5Data();
        $userData = array_merge($this->data, $userData);

        H5DfzjInvUsersLog::getUsers($this->websiteId, $this->h5Id, $this->user['id']);
        $countInvUsers = H5DfzjInvUsersLog::countUsers($this->websiteId, $this->h5Id, $this->user['id']);

        switch (true) {
            case $countInvUsers >= 1000:
                $getNum = 10; break;
            case $countInvUsers >= 500:
                $getNum = 8; break;
            case $countInvUsers >= 300:
                $getNum = 5; break;
            case $countInvUsers >= 200:
                $getNum = 3; break;
            case $countInvUsers >= 100:
                $getNum = 1; break;
            default:
                $getNum = 0;
        }
        $getNum = $getNum + 1;  // 每天额外赠送 1 次
        if ($userData['num']['day'] < date('Y-m-d')) {
            $userData['num']['day'] = date('Y-m-d');
            $userData['num']['useNum'] = 0;
        }
        $userData['num']['getNum'] = $getNum;

        return [$userData, $countInvUsers];
    }

    /**
     * 获取邀请用户 log
     * @param $userId
     * @return array
     */
    public function _getInvUsersLog($userId)
    {
        $data = H5DfzjInvUsersLog::getUsers($this->websiteId, $this->h5Id, $userId);
        return $data;
    }

    /**
     * 获取邀请礼包
     */
    public function actionGetInvGift()
    {
        $num = Cms::getPostValue('num');
        if (!$num) {
            $this->echoJson(6004);
        }
        if (!key_exists($num, $this->giftIdsInv)) {
            $this->echoJson(6005);
        }
        list($userData, $countInvUsers) = $this->_getH5Data();
        if ($countInvUsers < $this->giftIdsInvCondition[$num]) {
            $this->echoJson(6006);
        }
        $giftId = $this->giftIdsInv[$num];
        if ($userData['giftCodeLog'] && isset($userData['giftCodeLog'][$giftId])) {
            $userData['code'] = $userData['giftCodeLog'][$giftId];
            $this->echoJson(0, '', $userData);
        }
        list($code, $giftCodeLogId) = GiftCode::getGiftCodeOrEntity($this->websiteId, $giftId, '', $this->wxInfo['openid'], true, $this->h5Id, true);
        if ($code) {
            $userData['giftCodeLog'][$giftId] = $code;
            H5UserCenterData::setUserInfo($this->h5Id, $this->user['id'], $userData);
            $userData['code'] = $code;
            $this->echoJson(0, '', $userData);
        } else {
            $userData['code'] = $code;
            $this->echoJson(6012, '', $userData);
        }
    }

    /**
     * 进攻
     */
    public function actionAttack()
    {
        list($userData, $countInvUsers) = $this->_getH5Data();
        if (($userData['num']['getNum'] - $userData['num']['useNum']) < 1) {
            $this->echoJson(6001);
        }

        // 识别当前攻击目标
        $targetNum = 0;
        foreach ($userData['attackTarget'] as $k => $v) {
            if ($v['useBlood'] < $v['totalBlood']) {
                $targetNum = $k;
                break;
            }
        }
        if ($targetNum == 0) {
            $this->echoJson(6002);
        }

        $check = Cms::checkLock($this->websiteId, 'h5_dfzj_inv', $this->wxInfo['openid']);
        if (!$check) {
            $this->echoJson(6003);
        }
        $hurt = rand(1800, 3000);
        $nowUseBlood = $userData['attackTarget'][$targetNum]['useBlood'] + $hurt;

        $code = '';
        if ($nowUseBlood >= $userData['attackTarget'][$targetNum]['totalBlood']) {  // 当前目标已经攻击完成
            $userData['attackTarget'][$targetNum]['useBlood'] = $userData['attackTarget'][$targetNum]['totalBlood'];
            $giftId = $this->giftIdsAttack[$targetNum];
            list($code, $giftCodeLogId) = GiftCode::getGiftCodeOrEntity($this->websiteId, $giftId, '', $this->wxInfo['openid'], true, $this->h5Id, true);
            if ($code) {
                $userData['giftCodeLog'][$giftId] = $code;
            }
        } else {
            $userData['attackTarget'][$targetNum]['useBlood'] = $nowUseBlood;
        }

        $userData['num']['useNum'] = $userData['num']['useNum'] + 1;
        H5UserCenterData::setUserInfo($this->h5Id, $this->user['id'], $userData);

        H5DfzjInvHurtLog::addLog($this->websiteId, $this->h5Id, $this->user['id'], $targetNum, $hurt);  // 攻击Log
        Cms::clearLock($this->websiteId, 'h5_dfzj_inv', $this->wxInfo['openid']);
        $userData['code'] = $code;
        $userData['hurt'] = $hurt;
        $userData['targetNum'] = $targetNum;
        $this->echoJson(0, '', $userData);
    }

    /**
     * 为他助力
     */
    public function actionHelp()
    {
        $inviteCode = Cms::getPostValue('invite_code');
        if (!$inviteCode) {
            $this->echoJson('6008');
        }

        if ($inviteCode == $this->wxInfo['openid']) {
            $this->echoJson('6011');
        }

        // 验证邀请码是否正确
        $invUser = $this->_checkInviteUser($inviteCode);
        $invUserId = $invUser['id'];
        $invUsersLog = H5DfzjInvUsersLog::getUsers($this->websiteId, $this->h5Id, $invUserId);
        if ($invUsersLog && key_exists($this->user['id'], $invUsersLog)) {
            $this->echoJson('6010');
        }
        $startAt = strtotime(date('Y-m-d'));
        $endAt = strtotime(date('Y-m-d 23:59:59'));
        $count = 0;
        if ($invUsersLog && !empty($invUsersLog)) {
            foreach ($invUsersLog as $v) {
                if ($v['created_at'] >= $startAt && $v['created_at'] <= $endAt) {
                    $count++;
                }
            }
            if ($count >= 80) {
                $this->echoJson('6014');
            }
        }
        H5DfzjInvUsersLog::addLog($this->websiteId, $this->h5Id, $invUserId, $this->user['id'], $this->wxInfo['nickname']);
        $this->echoJson(0);
    }

    /**
     * 验证邀请码是否正确
     * @param $inviteCode
     * @return array|mixed|null|string|\yii\db\ActiveRecord
     */
    private function _checkInviteUser($inviteCode)
    {
        $invUser = H5UserCenter::getUserInfo($this->h5Id, '', $inviteCode);
        if (!$invUser) {
            $this->echoJson('6009');
        }
        return $invUser;
    }
}