<?php
namespace app\modules\gift\controllers;

use common\Cms;
use common\components\PcController;
use common\models\Gift;
use common\models\GiftCode;
use yii\helpers\Json;

/**
 * Created by yiicms.
 * User: Administrator
 * Author: druphliu@gmail.com
 * Date: 2015/6/12
 * Time: 19:35
 */
class HandleController extends PcController
{
    private $result = array('status' => 0,'msg'=>'');

    public function beforeAction($action, $isNoLayout = 0)
    {
        if($action->id!='get-code2'){
            $csrf = Cms::getGetValue('csrf');
            if ($csrf != Cms::getSession('csrf'));
                die(Json::encode($this->result));
        }
        return parent::beforeAction($action, $isNoLayout); // TODO: Change the autogenerated stub
    }

    public function actionGetCode()
    {
        $giftId = Yii::app()->request->getParam('gift_id');
        $phone = Yii::app()->request->getParam('phone');
        $type = Yii::app()->request->getParam('type', GiftCodeModel::CODE_TYPE_DEFAULT);
        $giftModel = GiftModel::model()->findByPk($giftId);
        if ($giftModel) {
            if (Utils::checkPhone($phone)) {
                $codeExit = GiftCodeModel::model()->find('gift_id=:gift_id and phone=:phone', array(':gift_id' => $giftId, ':phone' => $phone));
                if (!$codeExit) {
                    $code = GiftCodeModel::model()->find('gift_id=:gift_id and type=:type and phone is null', array(':gift_id' => $giftId, ':type' => $type));
                    if ($code) {
                        $code->send_at = time();
                        $code->phone = $phone;
                        $code->save();
                        $content = $giftModel->send_content ? str_replace('{code}', $code->code, $giftModel->send_content) : '礼包码为' . $code->code;
                        $smsResult = SmsUtils::sendSms($phone, $content);
                        $this->result['status'] = 1;//小主,礼包已发送至你的手机， 请查收。
                        $this->result['code'] = $code->code;
                    } else {
                        $this->result['status'] = -3;//您来晚了,礼包已领完
                        $this->result['msg'] = '您来晚了,礼包已领完';
                    };
                } else {
                    $this->result['status'] = -2;//礼包码已领取过
                    $this->result['code'] = $codeExit->code;
                    $this->result['msg'] = '礼包码已领取过';
                }
            } else {
                $this->result['status'] = -1;//手机号不正确
                $this->result['msg'] = '手机号不正确';
            }
        } else{
            $this->result['status'] =-4 ;//礼包类型不存在
            $this->result['msg'] = '礼包类型不存在';
        }
        $status = $this->result;
        echo CJSON::encode($status);
    }

    /*不需要输入手机号领取*/
    public function actionGetCode2()
    {
        $giftId = Cms::getGetValue('gift_id');
        $type = Cms::getGetValue('type', GiftCode::CODE_TYPE_DEFAULT);

        $giftModel = Gift::find($giftId);
        if ($giftModel) {
            $code = GiftCode::find()->where('gift_id=:gift_id and type=:type and send_at=0', array(':gift_id' => $giftId, ':type' => $type))->one();
            if ($code) {
                $code->send_at = time();
                $code->save();
                $content = $giftModel->send_content ? str_replace('{code}', $code->code, $giftModel->send_content) : '礼包码为' . $code->code;
                $this->result['status'] = 1;
                $this->result['msg'] = $content;
            } else {
                $this->result['msg'] ="礼包已领取完毕！" ;
            };
        }else{
            $this->result['msg'] ="请添加礼包类型！" ;
        }
        $b=CJSON::encode($this->result);
        echo "{$_GET['callback']}({$b})";
        exit;
    }

    public function actionRegister()
    {
        $phone = Yii::app()->request->getParam('phone');
        $giftId = Yii::app()->request->getParam('gift_id');
        $password = Yii::app()->request->getParam('password');
        $verify = Yii::app()->request->getParam('verifycode');
        $model = VerifyCodeModel::model()->find('phone=:phone and verify=:verify', array(':phone' => $phone, ':verify' => $verify));
        $giftModel = GiftModel::model()->findByPk($giftId);
        if ($giftModel) {
            if (Yii::app()->session['gift_verify_count'] >= 3) {//验证码超过次数
                $this->result['status'] = 3;
                die(CJSON::encode($this->result));
            }
            if ($model) {//验证码正确
                //注册
                $sign_str = '';
                $secret = '4315b694b76333aa6b689fb200612db8';

                $url = 'http://i.yingxiong.com/sdkApi/register?username=%s&password=%s&type=1&appkey=%s&sign=%s';
                $signData = array('username' => $phone, 'password' => $password, 'type' => 1);
                ksort($signData);
                foreach ($signData as $kk => $vv) {
                    if ($vv == '') continue;
                    $sign_str .= "{$kk}={$vv}&";
                }
                $sign_str .= $secret;
                $url = sprintf($url, $phone, $password, 'yingxiongXm', md5($sign_str));
                $result = file_get_contents($url);
                $data = json_decode($result);
                switch ($data->error) {
                    case 0:
                        $codeModel = GiftCodeModel::model()->find('phone is null and gift_id=:gift_id and type=0', array(':gift_id' => $giftId));//取新的
                        if ($codeModel) {
                            $codeModel->phone = $phone;
                            $codeModel->save();
                            $url = 'http://i.yingxiong.com/sdkApi/getAppUserCount?appkey=yingxiongXm';
                            $count = file_get_contents($url);
                            $data->count = $count ? $count : 0;
                            $this->result['status'] = 1;
                            $this->result['count'] = $count;
                            //发码
                            $content = $giftModel->send_content ? str_replace('{code}', $codeModel->code, $giftModel->send_content) : '礼包码为' . $codeModel->code;
                            SmsUtils::sendSms($phone, $content);
                        } else {
                            $this->result['status'] = 7;
                        }
                        break;
                    case 4:
                        //手机格式有误
                        $this->result['status'] = 4;
                        break;
                    case 5:
                        //密码有误
                        $this->result['status'] = 5;
                        break;
                    case 6:
                        //手机已经注册
                        $this->result['status'] = 6;
                        $codeModel = GiftCodeModel::model()->find('phone=:phone and gift_id=:gift_id and type=0', array(':phone' => $phone, ':gift_id' => $giftId));//是否已经领取了礼包码
                        if (!$codeModel) {
                            $codeModel = GiftCodeModel::model()->find('phone is null and gift_id=:gift_id and type=0', array(':gift_id' => $giftId));//取新的
                            $codeModel->phone = $phone;
                            $codeModel->send_at = time();
                            $codeModel->save();
                            //发码
                            $content = $giftModel->send_content ? str_replace('{code}', $codeModel->code, $giftModel->send_content) : '礼包码为' . $codeModel->code;
                            SmsUtils::sendSms($phone, $content);
                        }
                        break;
                }
            } else {
                //验证码有误
                $this->result['status'] = 5;
            }
            Yii::app()->session['gift_verify_count'] += 1;
        }
        die(CJSON::encode($this->result));
    }
    /*只注册不发礼包码*/
    public function actionRegister2()
    {
        $phone = Yii::app()->request->getParam('phone');
        $giftId = Yii::app()->request->getParam('gift_id');
        $password = Yii::app()->request->getParam('password');
        $verify = Yii::app()->request->getParam('verifycode');
        $model = VerifyCodeModel::model()->find('phone=:phone and verify=:verify', array(':phone' => $phone, ':verify' => $verify));
        if (Yii::app()->session['gift_verify_count'] >= 3) {//验证码超过次数
            $this->result['status'] = 3;
            die(CJSON::encode($this->result));
        }
        if ($model) {//验证码正确
            //注册
            $sign_str = '';
            $secret = '4f0dfbcdcbf6a5e81762eec135f80b6d';

            $url = 'http://i.yingxiong.com/sdkApi/register?username=%s&password=%s&type=1&appkey=%s&sign=%s';
            $signData = array('username' => $phone, 'password' => $password, 'type' => 1);
            ksort($signData);
            foreach ($signData as $kk => $vv) {
                if ($vv == '') continue;
                $sign_str .= "{$kk}={$vv}&";
            }
            $sign_str .= $secret;
            $url = sprintf($url, $phone, $password, 'yingxiongTtx5', md5($sign_str));
            $result = file_get_contents($url);
            $data = json_decode($result);
            switch ($data->error) {
                case 0:
                    $url = 'http://i.yingxiong.com/sdkApi/getAppUserCount?appkey=yingxiongTtx5';
                    $count = file_get_contents($url);
                    $data->count = $count ? $count : 0;
                    $this->result['status'] = 1;
                    $this->result['count'] = $count;
                    break;
                case 4:
                    //手机格式有误
                    $this->result['status'] = 4;
                    break;
                case 5:
                    //密码有误
                    $this->result['status'] = 5;
                    break;
                case 6:
                    //手机已经注册
                    $this->result['status'] = 6;
                    break;
            }
        } else {
            //验证码有误
            $this->result['status'] = 5;
        }
        Yii::app()->session['gift_verify_count'] += 1;

        die(CJSON::encode($this->result));
    }
    public function actionGetVerify()
    {

        $phone = Yii::app()->request->getParam('phone');
        $type = Yii::app()->request->getParam('type');
        $type = $type ? $type : 1;
        if (!$phone || !Utils::checkPhone($phone)) {
            echo CJSON::encode(array('status' => -1, 'msg' => '手机格式不正确'));
            exit;
        }

        /*
        //判断该用户是否已经注册过已经注册的话返回$this->result['status']=4
        $smsregister=file_get_contents("http://i.yingxiong.com/sdkApi/phoneExist?phone=".$phone);
        $result=json_decode($smsregister);
        if($result->status){
            $this->result['status']=4;
            die(CJSON::encode($this->result));
        }
        */
        //随机生成验证码
        $verify = rand(1000, 9999);
        //查看是否已经发送过,无论是否成功注册
        $model = VerifyCodeModel::model()->find('phone=:phone and type=:type', array(':phone' => $phone, ':type' => $type));
        if ($model) {
            if ($model->count >= 3)
                $this->result['status'] = 3;
            elseif ($model->created_at > time() - 30)//30秒内只能提交一次
                $this->result['status'] = 2;
            else {
                //重新发送验证码
                $model->verify = $verify;
                $model->created_at = time();
                $model->count += 1;
                $model->save();
                //发送短信
                if ($type == 2) {
                    $content = '验证码为:' . $verify . ',您正在领取礼包，请于1小时内输入';
                } else {
                    $content = '验证码为:' . $verify . ',您正在预约限量大礼包，请于1小时内输入';
                }

                $smsResult = SmsUtils::sendSms($phone, $content);
                $this->result['status'] = 1;
                Yii::app()->session['gift_verify_count'] = 0;
            }
        } else {
            $model = new VerifyCodeModel();
            if ($model) {
                $model->verify = $verify;
                $model->phone = $phone;
                $model->created_at = time();
                $model->count = 1;
                $model->type = $type;
                $model->save();
                //发送短信
                if ($type == 2) {
                    $content = '验证码为:' . $verify . ',您正在领取礼包，请于1小时内输入';
                } else {
                    $content = '验证码为:' . $verify . ',您正在预约限量大礼包，请于1小时内输入';
                }
                $smsResult = SmsUtils::sendSms($phone, $content);
                $this->result['status'] = 1;
                Yii::app()->session['gift_verify_count'] = 0;
            }
        }
        die(CJSON::encode($this->result));
    }

    /**
     * 获取礼包码
     */
    public function actiongetGift()
    {
        $phone = Yii::app()->request->getParam('phone');
        $giftId = Yii::app()->request->getParam('gift_id');
        $verify = Yii::app()->request->getParam('verify');
        $type = Yii::app()->request->getParam('verify_type');


        $model = VerifyCodeModel::model()->find('phone=:phone and type=:type and verify=:verify',
                array(':phone' => $phone, ':type' => $type, ':verify' => $verify));
        if ($model) {//验证码超过次数
            if (time() - $model->created_at > 3600) {
                echo CJSON::encode(array('status' => -1, 'msg' => '验证码已经过期'));exit;
            }
            $this->actionGetCode();
        } else {
            echo CJSON::encode(array('status' => -1, 'msg' => '验证码错误'));exit;
        }
    }
}
