<?php
/**
 * Created by PhpStorm.
 * User: lin.zhou
 * Date: 2019/1/28 0028
 * Time: 15:04
 */

namespace app\controllers;


use common\Cms;
use common\components\HomeController;
use common\models\GiftCode;
use common\models\UserCenter;
use common\models\UserCenterData;

class NewyearController extends HomeController
{
    CONST SESSION_LOGIN = 'tk_login_phone';
    CONST GIFT_NEWYEAR = 497; // 新年礼包

    // 签到礼包
    public $giftSign = [
        20190204 => 498,
        20190205 => 499,
        20190206 => 500,
        20190207 => 501,
        20190208 => 502,
        20190209 => 503,
        20190210 => 504,
        20190211 => 505,
    ];

    public $userData = [
        'gift_newyear' => '',   // 新年礼包
        'gift_sign' => [],
    ];

    public $now = '';

    public function beforeAction($action)
    {
        $this->now = date('Ymd');
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    /*
     * 获取用户信息
     */
    public function actionGetUserInfo()
    {
        list($user, $userData) = $this->_checkLogin();

        $userData['phone'] = $user['phone'];
        $userData['now'] = $this->now;
        $this->echoJson(0, '', $userData);
    }

    /**
     * 登录
     */
    public function actionLogin()
    {
        $phone = Cms::getPostValue('phone');
        $yzm = Cms::getPostValue('yzm');
        if (!$phone || !Cms::checkPhone($phone)) {
            $this->echoJson(1001);
        }
        $check = Cms::checkVerify(1);
        if ($check['status'] != 0) {
            $this->echoJson(1002);
        }

        $user = UserCenter::getUserInfo($this->website_id, $phone);
        if (!$user) {
            $user = UserCenter::addUser($this->website_id, $phone);
            $userData = $this->userData;

            list($code, $giftCodeLogId) = GiftCode::getGiftCodeByPhone($this->website_id, self::GIFT_NEWYEAR, $user['phone'], true);
            if ($code) {
                $userData['gift_newyear'] = $code;
            }

            UserCenterData::addData($this->website_id, $user['id'], $userData);
            $isNew = 1;
        } else {
            $userData = UserCenterData::getUserData($this->website_id, $user['id']);

            if (!isset($userData['gift_newyear']) || !$userData['gift_newyear']) {
                list($code, $giftCodeLogId) = GiftCode::getGiftCodeByPhone($this->website_id, self::GIFT_NEWYEAR, $user['phone'], true);
                if ($code) {
                    $userData['gift_newyear'] = $code;
                    UserCenterData::setData($this->website_id, $user['id'], $userData);
                }
            }
            $isNew = 0;
        }

        Cms::setSession(self::SESSION_LOGIN, $phone);
        $userData['now'] = $this->now;
        $userData['phone'] = $phone;
        $userData['is_new'] = $isNew;
        $this->echoJson(0, '', $userData);
    }

    /**
     * 检查登录
     */
    private function _checkLogin()
    {
        $phone = Cms::getSession(self::SESSION_LOGIN);
        if (!$phone) {
            $userData['now'] = $this->now;
            $this->echoJson(1, '', $userData);
        }
        $user = UserCenter::getUserInfo($this->website_id, $phone);
        if (!$user) {
            $userData['now'] = $this->now;
            $this->echoJson(1, '', $userData);
        }
        $userData = UserCenterData::getUserData($this->website_id, $user['id']);
        return [$user, $userData];
    }

    /**
     * 获取签到礼包
     */
    public function actionGetSignGift()
    {
        $start = 20190204;
        $end = 20190211;
        $now = $this->now;

        list($user, $userData) = $this->_checkLogin();
        $date = Cms::getPostValue('date');
        if ($date < $start || $date > $end) {
            $this->echoJson(1006);
        }
        if (isset($userData['gift_sign']) && isset($userData['gift_sign'][$date])) {
            $userData['now'] = $this->now;
            $userData['phone'] = $user['phone'];
            $this->echoJson(0, '', ['code' => $userData['gift_sign'][$date]['code'], 'user_data' => $userData]);
        }
        if ($date < $now) {
            $this->echoJson(1007);
        }
        if ($date > $now) {
            $this->echoJson(2, date("m月d日", strtotime($date)).'内签到才能获得礼包码哟~');
        }

        if ($now < $start || $now > $end) {
            $this->echoJson(2, date("m月d日", strtotime($date)).'内签到才能获得礼包码哟~');
        }

        if (!isset($this->giftSign[$now])) {
            $this->echoJson(1005);
        }
        list($code, $giftCodeLogId) = GiftCode::getGiftCodeByPhone($this->website_id, $this->giftSign[$now], $user['phone'], true);
        if (!$code) {
            $this->echoJson(1003);
        }
        $userData['gift_sign'][$now] = [
            'gift_id' => $this->giftSign[$now],
            'code' => $code,
            'created_at' => date('Y-m-d H:i:s'),
        ];
        UserCenterData::setData($this->website_id, $user['id'], $userData);
        $userData['now'] = $this->now;
        $userData['phone'] = $user['phone'];
        $this->echoJson(0, '', ['code' => $code, 'user_data' => $userData]);
    }

    public function actionLogout()
    {
        Cms::setSession(self::SESSION_LOGIN, '');
        $this->echoJson(0);
    }


}